### ISSUE TITLE
libjansson.so.4 not found

### ISSUE THREAD

**Issue by andriusst** [pkoutoupis/rapiddisk#117]
When running sudo rapiddisk I get the error message

`rapiddisk: error while loading shared libraries: libjansson.so.4: cannot open shared object file: No such file or directory`

 I built this from source on Clear Linux. ld did have some trouble locating libjasson.so file but I created some links and that did the trick. I built jasson-2.13.1 from source too but it looks like it didn't create its file links in all the places.

Can someone please give me a hint which location does rapiddisk expect this libjasson.so.4 file to be in?

**Comment by pkoutoupis** [comment]
To answer your question, rapiddisk does not expect libjansson to be in any specific directory. It relies on the underlying system to make the library accessible. Have you run an `ldconfig` after the installation?

**Comment by andriusst** [comment]
Yes, that was it! Thank you for a quick response!
