### ISSUE TITLE
How to erase/flush cashe only ?

### ISSUE THREAD

**Issue by marsalans** [pkoutoupis/rapiddisk#128]
rapiddisk -f not working

**Comment by pkoutoupis** [comment]
@marsalans Hello. This is fixed in this pull request: https://github.com/pkoutoupis/rapiddisk/pull/123. It should be merged into the master branch. soon.

**Comment by pkoutoupis** [comment]
This fix has been merged into master. Thank you for your help and interest in the project.

**Comment by marsalans** [comment]
> This fix has been merged into master. Thank you for your help and interest in the project.

Thanks.
