### ISSUE TITLE
Does it support creating RAM disk without "sudo" or "root" privilege?

### ISSUE THREAD

**Issue by lcmj520** [pkoutoupis/rapiddisk#136]
You know, as a user in CentOS cluster with slurm, no one has the privilege of "sudo". We cannot use "sudo apt install ..." or "mount  -t tmpfs -o size=1G tmpfs ./MyTmp".

So, does it support creating RAM disk without "sudo" or "root" privilege?

Thanks a lot.

**Comment by pkoutoupis** [comment]
@lcmj520 Unfortunately, sudo or root privileges are required as sysfs write access is needed.

**Comment by lcmj520** [comment]
> @lcmj520 Unfortunately, sudo or root privileges are required as sysfs write access is needed.

Oh my god! It seems everything I tried before is all in vain! 
![ZAI$49WXAXCY3`B$IHIQN7E](https://user-images.githubusercontent.com/69440987/197912895-145fd03d-5992-42f3-a567-6f6270deddc3.png)

Thanks a lot for your reply ....
