### ISSUE TITLE
how to install rapiddisk when jansson and libmicrohttpd was not install in /usr?

### ISSUE THREAD

**Issue by lcmj520** [pkoutoupis/rapiddisk#137]
The jansson and libmicrohttpd was install in /home/MyUser/jansson and /home/MyUser/libmicrohttpd respectively.

Then, I added the environments below to /home/MyUser/.bashrc:

#/home/MyUser/jansson
export C_INCLUDE_PATH=/home/MyUser/janssion/usr/local/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/home/MyUser/janssion/usr/local/include:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=/home/MyUser/janssion/usr/local/lib:$LIBRARY_PATH

#/home/MyUser/libmicrohttpd
export C_INCLUDE_PATH=/home/MyUser/libmicrohttpd/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/home/MyUser/libmicrohttpd/include:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=/home/MyUser/libmicrohttpd/lib:$LIBRARY_PATH

When I did "make" in rapiddisk folder, there were always errors:
 make -C src
make[1]: Entering directory `/home/MyUser/Download/rapiddisk-master/src'
gcc -c json.c -o json.o
json.c:31:10: fatal error: jansson.h: No such file or directory
   31 | #include <jansson.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [json.o] Error 1
make[1]: Leaving directory `/home/MyUser/Download/rapiddisk-master/src'
make: *** [src] Error 2

Could any one give some solutions? Thanks a lot!

**Comment by pkoutoupis** [comment]
@lcmj520 Please describe the build environment. Are only these two libraries and their headers in the "MyUser" home directory and you are relying on the system for everything else?

**Comment by matteotenca** [comment]
The current `Makefile` does not consider external variables, but `CC`. So you can try this:
```bash
$ CFLAGS="-I/home/MyUser/janssion/usr/local/include -I/home/MyUser/libmicrohttpd/include" LDFLAGS="-L/home/MyUser/janssion/usr/local/lib -ljansson -L/home/MyUser/libmicrohttpd/lib -lmicrohttpd" CC="cc $CFLAGS $LDFLAGS " make
```

**Comment by pkoutoupis** [comment]
@lcmj520 I know you were looking to build this suite and use with non-root access but did @matteotenca answer your question and if so, can we close this issue.

@matteotenca I think I will add your instructions into the Wiki. Thank you!

**Comment by pkoutoupis** [comment]
I will close this issue now since @matteotenca offered a temporary workaround. He is currently working on implementing this functionality in an update to a current PR https://github.com/pkoutoupis/rapiddisk/pull/139.
