### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alexmyczko** [pkoutoupis/rapiddisk#138]
Do you plan a new release within the next two months?

**Comment by pkoutoupis** [comment]
Yes. I will have a new release cut within the next month.

**Comment by pkoutoupis** [comment]
I will close this issue, as there is nothing else to do here. A new release will be coming very soon. Likely as soon as #139 gets merged.

**Comment by pkoutoupis** [comment]
@alexmyczko There is now a new 9.1.0 release that fixes a performance regression: https://github.com/pkoutoupis/rapiddisk/releases/tag/9.1.0

**Comment by alexmyczko** [comment]
https://buildd.debian.org/status/package.php?p=rapiddisk&suite=experimental
