### ISSUE TITLE
Implement OpenSUSE Kernel Module Packaging

### ISSUE THREAD

**Issue by bberberov** [pkoutoupis/rapiddisk#14]
The current OpenSUSE package does not automatically rebuild the modules during a kernel update.

The package should be updated to support OpenSUSE mechanisms for kernel module management.

See: https://en.opensuse.org/Kernel_Module_Packages

**Comment by pkoutoupis** [comment]
There does not seem to be an interest or any motivation to implement this. If there are any interested SUSE users who are able to help out with this, we can always reopen. Currently, openSUSE support utilizes dkms.

**Comment by bberberov** [comment]
I finally made OBS builds.  They are non-DKMS, following openSUSE guidelines.

This one targets the current release, 9.1.0: https://build.opensuse.org/package/show/home:bberberov/rapiddisk

This one is a sort of nightly: https://build.opensuse.org/package/show/home:bberberov:prj_test/rapiddisk

These will both need some testing.  I don't have the hardware for this at the moment.  There is a `longterm` kernel I'm trying to figure out how to target; hopefully resulting in more successful builds.

I'll try to expand on this as time allows.

**Comment by bberberov** [comment]
Not really, code-wise.  If there is a concise list of which releases support which kernel versions, I can try to add wider support for older Leap versions and SLE.  I'm not up to speed on kernel compatibility at the moment.

Tumbleweed/Slowroll will be a challenge to maintain.  The kernel version is constantly changing, and if there is an incompatibility, the build fails and there is no package published for the next system update.  Do you want me to file bugs when I notice this, or do you want to focus on kernel LTS compatibility?

I will need a better organization of the repositories on OBS before I can support a wider range of releases; I've realized this recently.  The links above :arrow_up:, and associated repos, will be changing, FYI.

**Comment by pkoutoupis** [comment]
LTS compatibility makes more sense. But only if it is worth the effort. I don't want you to spend more time than you should on chasing something that is difficult to pin down. And if any changes need to be made to the repo, just open a PR. Thanks again!
