### ISSUE TITLE
Current master 139 not compiling

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#146]
Hello.
Only reporting ...
Ubuntu 20.04.5 updated current date.
Downloaded the master 139 of 12-27-2022.

when doing make

make -C module 
make[1]: Entering directory '/tmp/3/11/module'
make -C /lib/modules/6.0.6-060006-generic/build M=/tmp/3/11/module
make[2]: Entering directory '/usr/src/linux-headers-6.0.6-060006-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-9 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  You are using:           gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  CC [M]  /tmp/3/11/module/rapiddisk.o
  CC [M]  /tmp/3/11/module/rapiddisk-cache.o
  MODPOST /tmp/3/11/module/Module.symvers
  CC [M]  /tmp/3/11/module/rapiddisk-cache.mod.o
  LD [M]  /tmp/3/11/module/rapiddisk-cache.ko
  BTF [M] /tmp/3/11/module/rapiddisk-cache.ko
Skipping BTF generation for /tmp/3/11/module/rapiddisk-cache.ko due to unavailability of vmlinux
  CC [M]  /tmp/3/11/module/rapiddisk.mod.o
  LD [M]  /tmp/3/11/module/rapiddisk.ko
  BTF [M] /tmp/3/11/module/rapiddisk.ko
Skipping BTF generation for /tmp/3/11/module/rapiddisk.ko due to unavailability of vmlinux
make[2]: Leaving directory '/usr/src/linux-headers-6.0.6-060006-generic'
make[1]: Leaving directory '/tmp/3/11/module'
make -C src 
make[1]: Entering directory '/tmp/3/11/src'
Creating Makefile utils.d
Creating Makefile sys.d
Creating Makefile rdsk.d
Creating Makefile rapiddiskd.d
Creating Makefile nvmet.d
Creating Makefile net.d
Creating Makefile main.d
Creating Makefile json.d
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c main.c -o main_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c utils.c -o utils_ndebug.o
utils.c:33:10: fatal error: pcre2.h: No such file or directory
   33 | #include <pcre2.h>
      |          ^~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:141: utils_ndebug.o] Error 1
make[1]: Leaving directory '/tmp/3/11/src'
make: *** [Makefile:37: src] Error 2

In same OS the previous master is compiled correctly.
Have an nice week.

**Comment by pkoutoupis** [comment]
@Augusto7743 Since the last merge (which will soon be 9.0.0, thanks to the hard work from @matteotenca), the minimum requirements have changed. This information is being updated in PR [https://github.com/pkoutoupis/rapiddisk/pull/145](https://github.com/pkoutoupis/rapiddisk/pull/145). Anyway, you will now need the following library and development packages to build the user space utilities:
> `libjansson`, `libpcre2-dev`, `libdevmapper` and `libmicrohttpd`

**Comment by Augusto7743** [comment]
Thanks for replying sharing the new requirements.
Thus I had installed the new requirements.

In Ubuntu 20.04.5 are installed
libjansson-dev 2.12-1build1
libpcre2-dev 10.39-3ubuntu0.1~20.04.sav0
libdevmapper-dev 2:1.02.167-1ubuntu1
libmicrohttpd-dev 0.9.66-1
libselinux1-dev 3.0-1build2

continue not being possible run make

the error message

make -C module 
make[1]: Entering directory '/tmp/3/2/module'
make -C /lib/modules/6.0.6-060006-generic/build M=/tmp/3/2/module
make[2]: Entering directory '/usr/src/linux-headers-6.0.6-060006-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-9 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  You are using:           gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  CC [M]  /tmp/3/2/module/rapiddisk.o
  CC [M]  /tmp/3/2/module/rapiddisk-cache.o
  MODPOST /tmp/3/2/module/Module.symvers
  CC [M]  /tmp/3/2/module/rapiddisk-cache.mod.o
  LD [M]  /tmp/3/2/module/rapiddisk-cache.ko
  BTF [M] /tmp/3/2/module/rapiddisk-cache.ko
Skipping BTF generation for /tmp/3/2/module/rapiddisk-cache.ko due to unavailability of vmlinux
  CC [M]  /tmp/3/2/module/rapiddisk.mod.o
  LD [M]  /tmp/3/2/module/rapiddisk.ko
  BTF [M] /tmp/3/2/module/rapiddisk.ko
Skipping BTF generation for /tmp/3/2/module/rapiddisk.ko due to unavailability of vmlinux
make[2]: Leaving directory '/usr/src/linux-headers-6.0.6-060006-generic'
make[1]: Leaving directory '/tmp/3/2/module'
make -C src 
make[1]: Entering directory '/tmp/3/2/src'
Creating Makefile utils.d
Creating Makefile sys.d
Creating Makefile rdsk.d
Creating Makefile rapiddiskd.d
Creating Makefile nvmet.d
Creating Makefile net.d
Creating Makefile main.d
Creating Makefile json.d
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c main.c -o main_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c utils.c -o utils_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c json.c -o json_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c rdsk.c -o rdsk_ndebug.o
In file included from /usr/include/string.h:495,
                 from common.h:36,
                 from rdsk.h:36,
                 from rdsk.c:30:
In function ‘strncpy’,
    inlined from ‘read_info’ at rdsk.c:148:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rdsk.c: In function ‘read_info’:
rdsk.c:147:8: note: length computed here
  147 |  len = strlen(buf);
      |        ^~~~~~~~~~~
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c nvmet.c -o nvmet_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c sys.c -o sys_ndebug.o
cc -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o rapiddisk main_ndebug.o utils_ndebug.o json_ndebug.o rdsk_ndebug.o nvmet_ndebug.o sys_ndebug.o  -ljansson -ldevmapper -lpcre2-8
In function ‘strncpy’,
    inlined from ‘read_info’ at rdsk.c:148:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin___strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^
rdsk.c: In function ‘read_info’:
rdsk.c:147:8: note: length computed here
  147 |  len = strlen(buf);
      |        ^
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c rapiddiskd.c -o rapiddiskd_ndebug.o
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c utils.c -o utils-server_ndebug.o
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c json.c -o json-server_ndebug.o
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c nvmet.c -o nvmet-server_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c net.c -o net_ndebug.o
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c rdsk.c -o rdsk-server_ndebug.o
In file included from /usr/include/string.h:495,
                 from common.h:36,
                 from rdsk.h:36,
                 from rdsk.c:30:
In function ‘strncpy’,
    inlined from ‘read_info’ at rdsk.c:148:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rdsk.c: In function ‘read_info’:
rdsk.c:147:8: note: length computed here
  147 |  len = strlen(buf);
      |        ^~~~~~~~~~~
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c sys.c -o sys-server_ndebug.o
cc -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o rapiddiskd rapiddiskd_ndebug.o utils-server_ndebug.o json-server_ndebug.o nvmet-server_ndebug.o net_ndebug.o rdsk-server_ndebug.o sys-server_ndebug.o  -ljansson -ldevmapper -lpcre2-8 -lmicrohttpd
In function ‘strncpy’,
    inlined from ‘read_info’ at rdsk.c:148:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin___strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^
rdsk.c: In function ‘read_info’:
rdsk.c:147:8: note: length computed here
  147 |  len = strlen(buf);
      |        ^
make[1]: Leaving directory '/tmp/3/2/src'
make -C test 
make[1]: Entering directory '/tmp/3/2/test'
cc     rxflush.c   -o rxflush
cc     rxio.c   -o rxio
cc     rxioctl.c   -o rxioctl
cc     rxro.c   -o rxro
make[1]: Leaving directory '/tmp/3/2/test'


The lines below are in log above.
Here I have added only for reference because in terminal are lines with changed colors about errors.

Creating Makefile json.d
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c main.c -o main_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c utils.c -o utils_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c json.c -o json_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c rdsk.c -o rdsk_ndebug.o
In file included from /usr/include/string.h:495,
                 from common.h:36,
                 from rdsk.h:36,
                 from rdsk.c:30:
In function ‘strncpy’,
    inlined from ‘read_info’ at rdsk.c:148:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rdsk.c: In function ‘read_info’:
rdsk.c:147:8: note: length computed here
  147 |  len = strlen(buf);
      |        ^~~~~~~~~~~


In file included from /usr/include/string.h:495,
                 from common.h:36,
                 from rdsk.h:36,
                 from rdsk.c:30:
In function ‘strncpy’,
    inlined from ‘read_info’ at rdsk.c:148:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rdsk.c: In function ‘read_info’:
rdsk.c:147:8: note: length computed here
  147 |  len = strlen(buf);
      |        ^~~~~~~~~~~

**Comment by pkoutoupis** [comment]
Those aren't errors. Check your source directory. The binary files are built and there. The messages you are seeing are gcc suggestions printed because of the build flags used.

**Comment by Augusto7743** [comment]
Thanks very much for saying it.
In moment not tested your software in kernel 6.1 or 6.1.1. My kernel sources are having build fails.
I need wait for an solution.
Have an nice week.

**Comment by pkoutoupis** [comment]
I added a note in the project Wiki: https://github.com/pkoutoupis/rapiddisk/wiki/Frequently-Asked-Questions-(FAQ)#why-am-i-seeing-warning-messages-saying-note-length-computed-here

**Comment by Augusto7743** [comment]
Installed and tested in Ubuntu 18.04.5 32 bits working correctly too ...

**Comment by Augusto7743** [comment]
Tested current master in Kernel 6.1.6.
Working correctly.
Have an nice week for you and the users.

**Comment by pkoutoupis** [comment]
@Augusto7743 I will close this issue since the original problem reported ended up being a non-issue. Thank you for testing all distros/kernels. It is very much appreciated. Feel free to continue reporting your testing in this ticket (even after it is closed). :-)

**Comment by Augusto7743** [comment]
Thanks for releasing 9.0.
Tested version 9.0 in Kernel 6.1.6 working correctly.
When possible will be installed kernel 6.2 for tests.

Have an nice week and good luck in your life and for users too.

**Comment by mhtvsSFrpHdE** [comment]
In case fedora users:  
A Beginner's Installation Setup Guide  
Installation steps for a dkms install.  
Load dependencies (Fedora 35):  
`sudo dnf install libmicrohttpd libmicrohttpd-devel jansson-devel kernel-headers kernel-devel dkms`

Then  
`sudo dnf install pcre2-devel device-mapper-devel`

**Comment by pkoutoupis** [comment]
@mhtvsSFrpHdE Thank you. I updated the Wiki: [https://github.com/pkoutoupis/rapiddisk/wiki/A-Beginner's-Installation---Setup-Guide](https://github.com/pkoutoupis/rapiddisk/wiki/A-Beginner's-Installation---Setup-Guide)

**Comment by Augusto7743** [comment]
Rapiddisk 9.0 installed on kernel 6.2.1. working correctly.
Amazing software !
An nice week for all users.
