### ISSUE TITLE
Is anyone still using RapidDisk on openSUSE 13 or even making use of the RESTful API?

### ISSUE THREAD

**Issue by pkoutoupis** [pkoutoupis/rapiddisk#17]
To help minimize my support workload, I was hoping to slowly start removing a distribution version or two starting in the next release. I wanted to quickly survey the users out there with the following question: Is anyone currently running RapidDisk on openSUSE 13 OR have you moved onto the Leap releases?

Also, are people out there actually using the RESTful API?

**Comment by bberberov** [comment]
The RESTful API makes me install PHP and a web server on OpenSUSE Tumbleweed.  The defaults (PHP and web server selected) were also not optimal, in my opinion.  I think the RESTful API could be reimplemented with a smaller dependency, later.

**Comment by pkoutoupis** [comment]
Honestly, I have been debating on either removing the API completely **OR** leveraging libmicrohttpd alongside libjansson and write a separate minimal daemon to listen on a specific port.

**Comment by pkoutoupis** [comment]
So, I have been staging 5.0. In it, I can rid of the dependency to PHP and a web server. Instead, I am linking libjansson to provide an addition config listing operation in JSON format.

Also, since I posted my question about openSUSE 13 here and on G+ and Facebook with no reply, I will assume that no one is really using the specific version of the distribution and if they are, I will rebuild it again.
