### ISSUE TITLE
Command "sudo rapiddisk -l -j|sed '1,3d'| jq" not any output

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#171]
Hello.
Thanks for reading my topic.
In https://github.com/pkoutoupis/rapiddisk/wiki/RapidDisk-Administration-Utility section "RapidDisk Management" about "To list all volumes in JSON format" the command
sudo rapiddisk -l -j|sed '1,3d'| jq
not show any output.
OS was installed jq

Only sharing that information ... not exactly support to how run statistics in json.

Have an nice week.

**Comment by pkoutoupis** [comment]
I need to fix that. The documentation is wrong. The sed portion should be removed and you should instead run: `sudo rapiddisk -l -j|jq`

**Comment by pkoutoupis** [comment]
I just fixed the errors in the documentation. Thank you for discovering it and bringing it to my attention.

**Comment by Augusto7743** [comment]
Thanks for replying the command.
closing.
