### ISSUE TITLE
[feature request] allow human readable notation for input

### ISSUE THREAD

**Issue by tobwen** [pkoutoupis/rapiddisk#176]
# feature request
Instead of `rapiddisk -a 20000` please allow to insert human readable notation `rapiddisk -a 20G` or `rapiddisk -a 20GiB`.

**Comment by matteotenca** [comment]
Hello, you may try #179.

Regards

**Comment by pkoutoupis** [comment]
https://github.com/pkoutoupis/rapiddisk/pull/179 has been merged. Thank you both!
