### ISSUE TITLE
Not is possible compile using gcc 12 with kernel compiled with gcc 9

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#182]
Hello.
Ubuntu 20.04.6 using kernel 6.6.5 and installed gcc 12.

When trying compile rapiddisk using "make"

make -C module 
make[1]: Entering directory '/tmp/3/module'
make -C /lib/modules/6.6.5-060605-generic/build M=/tmp/3/module
make[2]: Entering directory '/usr/src/linux-headers-6.6.5-060605-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-9 (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  You are using:           
  CC [M]  /tmp/3/module/rapiddisk.o
/bin/sh: 1: gcc-9: not found
make[4]: *** [scripts/Makefile.build:243: /tmp/3/module/rapiddisk.o] Error 127
make[3]: *** [/usr/src/linux-headers-6.6.5-060605-generic/Makefile:1919: /tmp/3/module] Error 2
make[2]: *** [Makefile:234: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.6.5-060605-generic'
make[1]: *** [Makefile:37: all] Error 2
make[1]: Leaving directory '/tmp/3/module'
make: *** [Makefile:29: module] Error 2

Is possible in same OS compile nvidia binary driver even if is required gcc with same version as kernel.
Have any way to compile using gcc 12 in kernel compiled with gcc 9 ? perhaps does more problems ?

Have an nice day.

**Comment by pkoutoupis** [comment]
I am not sure what to do with this. It is definitely a good question on whether it is even possible. In theory, I don't see why not. There isn't anything special going on with the Makefiles to prevent you from using GCC 12. I will need to find some time to recreate your environment to hopefully reproduce and understand.

**Comment by Augusto7743** [comment]
Hello pkoutoupis. All good with you ? Thanks for replying.

Also was done another test in other OS being Ubuntu 18.04.5 32 bits.
All dependencies are correctly installed.

Thus was done the command make


make -C module 
make[1]: Entering directory '/tmp/3/rd/module'
make -C /lib/modules/5.4.0-150-generic/build M=/tmp/3/rd/module
make[2]: Entering directory '/usr/src/linux-headers-5.4.0-150-generic'
  AR      /tmp/3/rd/module/built-in.a
  CC [M]  /tmp/3/rd/module/rapiddisk.o
  CC [M]  /tmp/3/rd/module/rapiddisk-cache.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC [M]  /tmp/3/rd/module/rapiddisk-cache.mod.o
  LD [M]  /tmp/3/rd/module/rapiddisk-cache.ko
  CC [M]  /tmp/3/rd/module/rapiddisk.mod.o
  LD [M]  /tmp/3/rd/module/rapiddisk.ko
make[2]: Leaving directory '/usr/src/linux-headers-5.4.0-150-generic'
make[1]: Leaving directory '/tmp/3/rd/module'
make -C src 
make[1]: Entering directory '/tmp/3/rd/src'
Creating Makefile utils.d
Creating Makefile sys.d
Creating Makefile rdsk.d
Creating Makefile rapiddiskd.d
Creating Makefile nvmet.d
Creating Makefile net.d
Creating Makefile main.d
Creating Makefile json.d
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c main.c -o main_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c utils.c -o utils_ndebug.o
utils.c: In function ‘preg_replace’:
utils.c:277:70: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Wformat=]
  277 |                 sprintf(result, "Error compiling regexp at offset #%ld: '%s'.", erroroffset, reg_error);
      |                                                                    ~~^          ~~~~~~~~~~~
      |                                                                      |          |
      |                                                                      long int   size_t {aka unsigned int}
      |                                                                    %d
utils.c: In function ‘validate_size’:
utils.c:508:77: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Wformat=]
  508 |                 sprintf(error_message, "Error compiling regexp at offset #%ld: '%s'.", erroroffset, reg_error);
      |                                                                           ~~^          ~~~~~~~~~~~
      |                                                                             |          |
      |                                                                             long int   size_t {aka unsigned int}
      |                                                                           %d
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c json.c -o json_ndebug.o                                                                                            
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c rdsk.c -o rdsk_ndebug.o                                                                                            
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c nvmet.c -o nvmet_ndebug.o                                                                                          
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c sys.c -o sys_ndebug.o                                                                                              
cc -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o rapiddisk main_ndebug.o utils_ndebug.o json_ndebug.o rdsk_ndebug.o nvmet_ndebug.o sys_ndebug.o  -ljansson -ldevmapper -lpcre2-8 -lm                                                                                                                                                                                                             
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c rapiddiskd.c -o rapiddiskd_ndebug.o                                                                                
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c utils.c -o utils-server_ndebug.o                                                                          
utils.c: In function ‘preg_replace’:
utils.c:277:70: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Wformat=]
  277 |                 sprintf(result, "Error compiling regexp at offset #%ld: '%s'.", erroroffset, reg_error);
      |                                                                    ~~^          ~~~~~~~~~~~
      |                                                                      |          |
      |                                                                      long int   size_t {aka unsigned int}
      |                                                                    %d
utils.c: In function ‘validate_size’:
utils.c:508:77: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Wformat=]
  508 |                 sprintf(error_message, "Error compiling regexp at offset #%ld: '%s'.", erroroffset, reg_error);
      |                                                                           ~~^          ~~~~~~~~~~~
      |                                                                             |          |
      |                                                                             long int   size_t {aka unsigned int}
      |                                                                           %d
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c json.c -o json-server_ndebug.o
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c nvmet.c -o nvmet-server_ndebug.o
cc -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c net.c -o net_ndebug.o
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c rdsk.c -o rdsk-server_ndebug.o
cc -Wdate-time -DSERVER -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c sys.c -o sys-server_ndebug.o
cc -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o rapiddiskd rapiddiskd_ndebug.o utils-server_ndebug.o json-server_ndebug.o nvmet-server_ndebug.o net_ndebug.o rdsk-server_ndebug.o sys-server_ndebug.o  -ljansson -ldevmapper -lpcre2-8 -lmicrohttpd -lm
Successfully built all rapiddisk and rapiddiskd binary files.
make[1]: Leaving directory '/tmp/3/rd/src'
make -C test 
make[1]: Entering directory '/tmp/3/rd/test'
cc     rxflush.c   -o rxflush
cc     rxio.c   -o rxio
cc     rxioctl.c   -o rxioctl
cc     rxro.c   -o rxro
make[1]: Leaving directory '/tmp/3/rd/test'



after using command gcc -v

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/12/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 12.3.0-1ubuntu1~18.04.sav1' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=i686-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-targets=all --enable-multiarch --disable-werror --disable-cet --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~18.04.sav1) 




How you see in 18.04 even with kernel and gcc not being the same version was possible complete the compilation.
Now in 20.04 not is possible. The same problem happen if trying install nvidia binary driver. However is possible avoid the binary driver error using an alternate command line.

have done an search in some forums and sites about it ... not is simple figure ... some users and programmers say to use gcc with same version used to compile the kernel and others say to only gcc have the version above and kernel an version below and even so happen problems with OS libc version.

Only trying understand about it and sharing information.

**Comment by Augusto7743** [comment]
trying with
make HOSTCC=gcc-12 CC=gcc-12


make -C module 
make[1]: Entering directory '/tmp/3/rd/module'
make -C /lib/modules/6.6.5-060605-generic/build M=/tmp/3/rd/module
make[2]: Entering directory '/usr/src/linux-headers-6.6.5-060605-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-9 (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~20.04.sav4) 12.3.0
  CC [M]  /tmp/3/rd/module/rapiddisk.o
  CC [M]  /tmp/3/rd/module/rapiddisk-cache.o
  MODPOST /tmp/3/rd/module/Module.symvers
  CC [M]  /tmp/3/rd/module/rapiddisk.mod.o
  LD [M]  /tmp/3/rd/module/rapiddisk.ko
  BTF [M] /tmp/3/rd/module/rapiddisk.ko
Skipping BTF generation for /tmp/3/rd/module/rapiddisk.ko due to unavailability of vmlinux
  CC [M]  /tmp/3/rd/module/rapiddisk-cache.mod.o
  LD [M]  /tmp/3/rd/module/rapiddisk-cache.ko
  BTF [M] /tmp/3/rd/module/rapiddisk-cache.ko
Skipping BTF generation for /tmp/3/rd/module/rapiddisk-cache.ko due to unavailability of vmlinux
make[2]: Leaving directory '/usr/src/linux-headers-6.6.5-060605-generic'
make[1]: Leaving directory '/tmp/3/rd/module'
make -C src 
make[1]: Entering directory '/tmp/3/rd/src'
Creating Makefile utils.d
Creating Makefile sys.d
Creating Makefile rdsk.d
Creating Makefile rapiddiskd.d
Creating Makefile nvmet.d
Creating Makefile net.d
Creating Makefile main.d
Creating Makefile json.d
gcc-12 -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c main.c -o main_ndebug.o
gcc-12 -Wdate-time -O2 -Wno-unused-result -flto=auto -ffat-lto-objects -fstack-protector-strong -c utils.c -o utils_ndebug.o
utils.c:36:10: fatal error: pcre2.h: No such file or directory
   36 | #include <pcre2.h>
      |          ^~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:142: utils_ndebug.o] Error 1
make[1]: Leaving directory '/tmp/3/rd/src'
make: *** [Makefile:37: src] Error 2

**Comment by pkoutoupis** [comment]
```
utils.c:36:10: fatal error: pcre2.h: No such file or directory
36 | #include <pcre2.h>
```
This dependency is not installed. You will need `libpcre2-dev` or whatever it is named in your distro release.

BUT based on what I am seeing with your last post, setting:
```
make HOSTCC=gcc-12 CC=gcc-12
```

If you fix that, it looks as if the rest will succeed.

**Comment by Augusto7743** [comment]
Strange .. I need analyze it.
I have installed libpre2-dev more recent version
libpcre2-16-0_10.34-7ubuntu0.1_amd64.deb

before was installed libpcre2-8-0_10.34-7ubuntu0.1_amd64

I will to do an test and reply soon.
