### ISSUE TITLE
Build error with kernel 6.10

### ISSUE THREAD

**Issue by manualinux** [pkoutoupis/rapiddisk#187]
When compiling the module with kernel 6.10, the following error message occurs:

```
drivers/block/rapiddisk/rapiddisk-cache.c:1045:47: error: no member named 'bd_inode' in 'struct block_device'
 1045 |                 dmc->size = to_sector(dmc->cache_dev->bdev->bd_inode->i_size);
      |                                       ~~~~~~~~~~~~~~~~~~~~  ^
drivers/block/rapiddisk/rapiddisk-cache.c:1081:45: error: no member named 'bd_inode' in 'struct block_device'
 1081 |         dev_size = to_sector(dmc->cache_dev->bdev->bd_inode->i_size);
      |                              ~~~~~~~~~~~~~~~~~~~~  ^
2 errors generated.
```
The [link](https://github.com/torvalds/linux/commit/38da32ee70b876f5b8bea7c4135eff46339c18f2) to the kernel code modification that produces the error.

Regards

**Comment by anbe42** [comment]
Can we replace `to_sector(dmc->cache_dev->bdev->bd_inode->i_size)` with `bdev_nr_sectors(dmc->cache_dev->bdev)` ?
`bdev_nr_sectors()` was introduced in Linux v5.11 (https://github.com/torvalds/linux/commit/a782483cc1f875355690625d8253a232f2581418)

**Comment by pkoutoupis** [comment]
I will need to look into this, although time has not been kind to me lately and I do apologize for the delay in everything.

**Comment by manualinux** [comment]
> Can we replace `to_sector(dmc->cache_dev->bdev->bd_inode->i_size)` with `bdev_nr_sectors(dmc->cache_dev->bdev)` ? `bdev_nr_sectors()` was introduced in Linux v5.11 ([torvalds/linux@a782483](https://github.com/torvalds/linux/commit/a782483cc1f875355690625d8253a232f2581418))

I have tested it and it works. Thanks for the contribution. @anbe42

**Comment by pkoutoupis** [comment]
@manualinux Put together a pull request and I can review to merge.

**Comment by pkoutoupis** [comment]
Merged. Thank you!
