### ISSUE TITLE
Cannot cache-map device 

### ISSUE THREAD

**Issue by ferdavs** [pkoutoupis/rapiddisk#21]
I am trying to cache my _/opt_ which is on other disk (/dev/sda4)
I did unmount sda4

sudo rapiddisk --cache-map rd0 /dev/sda4

gives this error:
**device-mapper: reload ioctl on rc-wt_sda4 failed: Invalid argument
Command failed
Error. Unable to create map. Please verify all input values are correct.**

**Comment by pkoutoupis** [comment]
What does syslog say? Does it say something along the lines of "resource busy" coming from device mapper?

If so, you need to umount the volume, create the mapping, and then mount the newly created device mapper node in /dev/mapper/.

**Comment by ferdavs** [comment]
I did these and it worked as you said:

umount -f /dev/sda4
rapiddisk --attach 2048
rapiddisk --cache-map rd0 /dev/sda4
mount /dev/mapper/rc-wt_sda4

**Comment by ferdavs** [comment]
Worked until reboot
syslog:
 **device-mapper: table: 253:0: rapiddisk-cache: rapiddisk-cache: Disk device lookup failed
 device-mapper: ioctl: error adding target to table**

**Comment by ferdavs** [comment]
sorry for this.
it was not unmounted properly
