### ISSUE TITLE
Compiling for Arch Linux ARMv8.

### ISSUE THREAD

**Issue by BobbyBabes** [pkoutoupis/rapiddisk#25]
@pkoutoupis Do you foresee any roadblocks with compiling Rapiddisk for [Arch Linux ARM](https://archlinuxarm.org) (ARMv8) ?
I'm waiting for the RockPro64 board to be released (later this month hopefully). And it would influence my decision about whether to go for a 2 or 4GB version of the board.

Thanks already.

**Comment by pkoutoupis** [comment]
I used to build this suite for the ARMv7 without issue, although the boards I was using were about 1GB in size. I do not do anything architecture/DIMM size specific, so I doubt that you will see any obvious impacts of running this code on your box with the 4GB. If you do, then I will be more than happy to help you out and get whatever issues resolved.

**Comment by BobbyBabes** [comment]
That sounds wonderful. :) And thanks for offering help in case it's needed.

**Comment by pkoutoupis** [comment]
Not a problem. Just open a new issue if you stumble on anything. Best of luck!
