### ISSUE TITLE
fatal error: jansson.h: No such file or directory

### ISSUE THREAD

**Issue by Adyel** [pkoutoupis/rapiddisk#27]
Hello,

When I try to compile the code. I get this error. How can I resolve this? NB: I am trying this program for the first time. So, still not sure how it works. What does `RapidDisk-Cache` actually does can you please explain in an easier way?

Thanks for your Time :) 

![image](https://user-images.githubusercontent.com/4653623/41196185-75432efc-6c5c-11e8-96d2-c24018dc57f7.png)

**Comment by pkoutoupis** [comment]
The README of the package defines the library dependencies required to build this package.
* zlib
* libcryptsetup
* libjansson

Based on the error above, you are missing libjansson. Be sure you go to your distributions package repository and install not only the library but the developer packages (of all three) as well.

RapidDisk-Cache enable RapidDisk RAM drives as a front end Read Cache for slower disk devices. It uses a FIFO LRU caching policy and has been known to dramatically boost read performance of standard server and desktop machines.

**Comment by Adyel** [comment]
Yes, you may close it. Sadly all these dependencies are not available in my distribution repository. I really don't want to maintain them manually. I tried the pre-built binary. It did not work out that well. So, I opted for `preload`.

Thanks a lot for your time. Really appreciate it :+1:

**Comment by pkoutoupis** [comment]
I understand. Thank you!
