### ISSUE TITLE
Compiling on ARM v7

### ISSUE THREAD

**Issue by sadnblueish** [pkoutoupis/rapiddisk#31]
Hi,

While compiling on Raspberry Pi3b and Orange Pi Plus 2E I get error.
[output.txt](https://github.com/pkoutoupis/rapiddisk/files/2752679/output.txt)

Raspberry:
Linux DietPi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

OrangePi:
Linux orangepiplus2e 4.14.84-sunxi #3 SMP Sat Dec 1 07:18:41 CET 2018 armv7l armv7l armv7l GNU/Linux

**Comment by pkoutoupis** [comment]
I will need to add support for the ARM architecture.

**Comment by sadnblueish** [comment]
Hi, 
Just following up on the request, did you get chance to add support for ARM?

**Comment by pkoutoupis** [comment]
Thank you for following up. I will be sure to carve out some time in the next week or so and will start sending you code to test out once changes have been made.

**Comment by pkoutoupis** [comment]
@sadnblueish: I was able to reproduce the compilation warnings/errors here. I should have a testable branch for you this weekend.

**Comment by pkoutoupis** [comment]
OK, I lied. I have a branch available for testing now: `defect/armv7support` :-D

Please run a `make clean` from the root of the project, then `git pull` to get the latest, then `git checkout defect/armv7support` to get these changes. Rerun the `make` and let me know what happens.

**Comment by sadnblueish** [comment]
Will get back soon!

**Comment by sadnblueish** [comment]
Make process went successful on Raspberry Pi 3b. I did a quick cache-map and it was successful. Will test further later but seems fine.

**Comment by pkoutoupis** [comment]
Awesome. I will run a few tests myself on non-ARM builds before officially merging. Thank you again!

**Comment by pkoutoupis** [comment]
Tested on both x86_64 and armv7. Commit ID: bd38ab6441a60ae667fee02822e725f6e852a280
