### ISSUE TITLE
How do I create a ramdisk specific ramdisk (i.e. rd1) with specific size (i.e. 2048 MB)?

### ISSUE THREAD

**Issue by hiredgunhouse** [pkoutoupis/rapiddisk#33]
See title.
It seem that when using --attach function I cannot specify rd1 as ramdisk that I want to create. Seems that rapiddisk is deciding which ramdisk will be created.
This makes it harder to create scripts that use rapiddisk.
Any advice?

**Comment by pkoutoupis** [comment]
The reason why I prevent the user from naming the ram drive is to avoid a condition in where the user may accidentally name 2 drives the same name which could eventually lead to a kernel panic. The numbers are created in the order in which the attach command is issued and if you remove any in between a listing, a newly created drive will replace the name of a previously removed one. For instance, if you have rd0, rd1 & rd2 and I decide to remove rd1, the next drive created is rd1 and the one after that rd3.

Either way, if your script does not "fork" or run subscripts that invoke the attach command, you should be able to maintain order and knowledge of what was created. Also, you could rely on the --list option to see what has already been created and what hasn't alongside their respective sizes in MB. Another mechanism by which you can see what has been created + size is to traverse the /sys/block path which is what the --list command does. The latter approach of which will require less string manipulation.

If this explanation does not help, just let me know what you are attempting to do and maybe we can brainstorm together on the best approach.

**Comment by hiredgunhouse** [comment]
Ok, I'll try to improve my scripting skills then :)
Thank you.
