### ISSUE TITLE
Should VERSION in this Makefile set to 6.0? dkms problem with versions already present

### ISSUE THREAD

**Issue by Shub77** [pkoutoupis/rapiddisk#35]
In `module/Makefile`, `VERSION` is set to `5.2`. This gave me an error on `make dkms`, since a 5.2 version was already present in dkms. Furthermore, maybe you should `dkms remove` the module first anyway: this would prevent the `make dkms` command fail every time but the first.

    shub@WarHP:~/rapid6.0/rapiddisk-6.0$ sudo make dkms
    cd module; make dkms; cd ..
    make[1]: Entering directory '/home/shub/rapid6.0/rapiddisk-6.0/module'
    sudo mkdir -pv /usr/src/rapiddisk-6.0/
    sudo cp -v * /usr/src/rapiddisk-6.0/
    'Makefile' -> '/usr/src/rapiddisk-6.0/Makefile'
    'Module.symvers' -> '/usr/src/rapiddisk-6.0/Module.symvers'
    'dkms.conf' -> '/usr/src/rapiddisk-6.0/dkms.conf'
    'modules.order' -> '/usr/src/rapiddisk-6.0/modules.order'
    'rapiddisk-cache.c' -> '/usr/src/rapiddisk-6.0/rapiddisk-cache.c'
    'rapiddisk-cache.ko' -> '/usr/src/rapiddisk-6.0/rapiddisk-cache.ko'
    'rapiddisk-cache.mod.c' -> '/usr/src/rapiddisk-6.0/rapiddisk-cache.mod.c'
    'rapiddisk-cache.mod.o' -> '/usr/src/rapiddisk-6.0/rapiddisk-cache.mod.o'
    'rapiddisk-cache.o' -> '/usr/src/rapiddisk-6.0/rapiddisk-cache.o'
    'rapiddisk.c' -> '/usr/src/rapiddisk-6.0/rapiddisk.c'
    'rapiddisk.ko' -> '/usr/src/rapiddisk-6.0/rapiddisk.ko'
    'rapiddisk.mod.c' -> '/usr/src/rapiddisk-6.0/rapiddisk.mod.c'
    'rapiddisk.mod.o' -> '/usr/src/rapiddisk-6.0/rapiddisk.mod.o'
    'rapiddisk.o' -> '/usr/src/rapiddisk-6.0/rapiddisk.o'
    'rapiddisk.o.ur-safe' -> '/usr/src/rapiddisk-6.0/rapiddisk.o.ur-safe'
    'rapiddisk.txt' -> '/usr/src/rapiddisk-6.0/rapiddisk.txt'
    sudo dkms add -m rapiddisk -v 5.2
    Error! DKMS tree already contains: rapiddisk-5.2
    You cannot add the same module/version combo more than once.
    Makefile:53: recipe for target 'dkms' failed
    make[1]: *** [dkms] Error 3
    make[1]: Leaving directory '/home/shub/rapid6.0/rapiddisk-6.0/module'
    shub@WarHP:~/rapid6.0/rapiddisk-6.0$

**Comment by pkoutoupis** [comment]
You are correct. This should be addressed. Thank you for catching this. I can do it myself, or if you want to do a pull request to capture all of this, that would be great as well.

Yes, the Makefile should read 6.0. As for removing old versions, some mechanism will need to sweep through to see what is already installed.

**Comment by pkoutoupis** [comment]
OK. I pushed the bug fix to master. It will address the Makefile error. As for the removal of older DKMS versions, I created a new ticket #36 to track it as a separate enhancement.
