### ISSUE TITLE
Enhance DKMS installation process

### ISSUE THREAD

**Issue by pkoutoupis** [pkoutoupis/rapiddisk#36]
Iterate through all DKMS installs of `rapiddisk` on the current kernel version and remove. Generate list using something like this:

```
sudo dkms status rapiddisk|tr -s '[[:space:]]' ','|cut -f2-3 -d','
```

**Comment by Shub77** [comment]
Hi there, sorry for answering so late!

Have a look at my commit if you want, I tested it on Ubuntu 18.04.2.

This approach preserves/does not touch other versions of rapiddisk already installed via dkms and does not touch other rapiddisk insallations on different kernel versions than the current.

This is good cause you can experiment on the older kernel version before switching to the main one and install rapiddisk on it.

Let me know!

Regards

**Comment by pkoutoupis** [comment]
I will test it out this weekend. Thank you!

**Comment by pkoutoupis** [comment]
This was addressed in https://github.com/pkoutoupis/rapiddisk/pull/37.

**Comment by pkoutoupis** [comment]
Thank you very much @Shub77. You are always welcome to contribute as you see fit. It was a pleasure working with you.

**Comment by Shub77** [comment]
Thanks!!
