### ISSUE TITLE
Enhancement: script for initramfs to init rapiddisk on boot and/or use it for boot volume

### ISSUE THREAD

**Issue by Shub77** [pkoutoupis/rapiddisk#38]
Hi,
since I wanted to use rapiddisk for my boot partition/volume, I wrote what was needed by initramfs to add the modules and init them, and add a cache via rapiddisk command, during boot time. There is some work to do yet, but if you're interested I can pull them someway.

Regards

**Comment by pkoutoupis** [comment]
I would love to see these changes. I am not entirely sure how or where they will fit and if I have any reservations, I will be sure to let you know.

**Comment by Shub77** [comment]
Ok, I'll give you some more infos.
I wrote two (ultrasimple to be honest) scripts in respect of the `initramfs-tools` docs,: the first to add new/specific modules and/or executable files to the final `initrd` files (it is called hook script), and the second one to execute or do something at boot time (this one is called boot script), during one or more of the boot process phases.

The hook script simply instruct `initramfs-tools` to add (copy) the `rapiddisk`'s modules and the `rapiddisk` executable itself to the final `initrd` file, upon update or creation of the latter; while the boot script, which is copied inside the `initrd` file too, is invoked during the boot process and barely execute one or more `rapiddisk` commands with the wanted parameters.

This way is possibile to add any cache to any drive at boot time, but it really comes in hand if you want to use `rapiddisk` on your root partition. Since it is not possible to add a cache on mounted filesystems, we have to do it before the `/` is mounted: with `initramfs-tools` scripts becomes possible to activate a rapiddisk cache on the boot partition *before* `/` is mounted, to take advantage of the cache on the root partition too. Something like this:

    shub@gturismo:~$ lsinitramfs /boot/initrd.img-4.15.0-55-generic |grep rapiddisk
    lib/modules/4.15.0-55-generic/updates/dkms/rapiddisk.ko
    lib/modules/4.15.0-55-generic/updates/dkms/rapiddisk-cache.ko
    sbin/rapiddisk
    scripts/init-premount/rapiddisk
    shub@gturismo:~$

the hook script looks something like this:

    #!/bin/sh
    PREREQ=""
    prereqs()
    {
            echo "$PREREQ"
    }

    case "${1}" in
    prereqs)
            prereqs
            exit 0
            ;;
    esac

    . /usr/share/initramfs-tools/hook-functions

    # Begin real processing below this line

    manual_add_modules rapiddisk
    manual_add_modules rapiddisk-cache
    copy_exec /sbin/rapiddisk /sbin

    exit 0

and the boot script something like this:

    #!/bin/sh
    PREREQ=""
    prereqs()
    {
            echo "$PREREQ"
    }

    case "${1}" in
    prereqs)
            prereqs
            exit 0
            ;;
    esac

    # Begin real processing below this line

    modprobe rapiddisk
    modprobe rapiddisk-cache
    rapiddisk --attach 300
    rapiddisk --cache-map rd0 /dev/sdb3 wa

    exit 0

Regards

**Comment by pkoutoupis** [comment]
I am trying to figure out how to make this one fit. I think it would be a good addition but does it make sense to place it in the source repository or would it make more sense to throw it into the project Wiki? I like the idea. And many have asked for something similar over the years.

**Comment by chabad360** [comment]
I would add it as a feature, because it would probably make rapiddisk significantly more useful. Plus, it would make setup much easier.

**Comment by ay-b** [comment]
Guys, any news on it? 

@Shub77 Could you, please, be a little more specific on manual setup for your scripts? I don't get where I should put them. 

Also there is no (more?) target for the "sudo make dkms". Is it fine or I'm missing something?

**Comment by pkoutoupis** [comment]
@ay-b : It is now `make dkms-install` and `make dkms-uninstall`.

**Comment by Shub77** [comment]
Hey all,

sorry if I'm answering only now.

`update-initramfs` looks for some scripts when invoked. To semplify, there are two kind of them, one is called `hook script` and is intended to add (copy) modules and/or executables in the root of the final initrd.img file that will be written in `/boot/`, the other kind contains some commands to be executed at some point of the boot process.

If you list `/usr/share/initramfs-tools` you can see this (Ubuntu):

    shub@WarHP:~$ ll /usr/share/initramfs-tools
    total 36
    drwxr-xr-x 1 root root   128 May 19 05:58 ./
    drwxr-xr-x 1 root root  5962 May 19 07:56 ../
    drwxr-xr-x 1 root root    68 May 19 07:51 conf-hooks.d/
    drwxr-xr-x 1 root root     0 Oct 13  2017 conf.d/
    -rw-r--r-- 1 root root 24275 Feb 18 02:19 hook-functions
    drwxr-xr-x 1 root root   558 May 19 07:53 hooks/
    -rwxr-xr-x 1 root root  7424 Apr  2 06:31 init*
    -rw-r--r-- 1 root root   357 Feb 15 01:42 modules
    drwxr-xr-x 1 root root     0 Oct 13  2017 modules.d/
    drwxr-xr-x 1 root root   200 May 19 07:12 scripts/
    shub@WarHP:~$

in the `hooks` directory there are plenty of hook scripts, i.e. the one called `btrfs` tells `update-initrd` to include the `btrfs` and `fsck.btrfs` executables into the `initrd.img` file.

If we place in this directory a file called for example `rapiddisk_hook` we can instruct `update-initrd` to include the files needed by Rapiddisk to run: two kernel modules and the `rapiddisk` executable.

This is a working example, to be put in `/usr/share/initramfs-tools/hooks/` as `rapiddisk_hook`  (remeber to `chmod +x` the file, working as root):

    #!/bin/sh
    PREREQ=""
    prereqs()
    {
            echo "$PREREQ"
    }
    
    case "${1}" in
    prereqs)
            prereqs
            exit 0
            ;;
    esac

    . /usr/share/initramfs-tools/hook-functions

    # Begin real processing below this line
    
    manual_add_modules rapiddisk
    manual_add_modules rapiddisk-cache
    copy_exec /sbin/rapiddisk /sbin

    exit 0

The three lines that follows are the ones which make the job of adding two modules and the executable to the final `initrd.img` tree:

    manual_add_modules rapiddisk
    manual_add_modules rapiddisk-cache
    copy_exec /sbin/rapiddisk /sbin

The commands `manual_add_modules` and `copy_exec` are macros included from the line:

    . /usr/share/initramfs-tools/hook-functions

The second script we have to create does the real job: calls the rapiddisk executable to create the cached volume.

In  `/usr/share/initramfs-tools/script` directory there are some subdirs which represents different stages of the boot process:

    shub@WarHP:~$ ll /usr/share/initramfs-tools/scripts/
    total 36
    drwxr-xr-x 1 root root   200 May 19 07:12 ./
    drwxr-xr-x 1 root root   128 May 19 05:58 ../
    -rw-r--r-- 1 root root 21392 Apr  8 22:22 functions
    drwxr-xr-x 1 root root    24 May 19 07:05 init-bottom/
    drwxr-xr-x 1 root root    74 May 19 19:24 init-premount/
    drwxr-xr-x 1 root root   116 May 19 07:53 init-top/
    -rw-r--r-- 1 root root  7577 Feb 18 02:19 local
    drwxr-xr-x 1 root root    18 May 19 07:12 local-block/
    drwxr-xr-x 1 root root    62 May 19 07:12 local-bottom/
    drwxr-xr-x 1 root root    62 May 19 07:51 local-premount/
    drwxr-xr-x 1 root root    40 May 19 07:12 local-top/
    -rw-r--r-- 1 root root  3093 Feb 15 01:42 nfs
    drwxr-xr-x 1 root root    42 May 19 07:05 panic/
    shub@WarHP:~$

These are documented in `man initramfs-tools`.
The one we are interested in is `init-premount`. From docs:

> init-premount happens after modules specified by hooks and /etc/initramfs-tools/modules have been loaded.

So, here we have to place a so-called `boot script` which loads the modules and invokes `rapiddisk` to create the cached device.

In `/usr/share/initramfs-tools/script/init-premount` we can create a file named, for example, `rapiddisk` as `root`, as an executable (`chmod +x`), with this contents:

    #!/bin/sh
    PREREQ=""
    prereqs()
    {
            echo "$PREREQ"
    }

    case "${1}" in
    prereqs)
            prereqs
            exit 0
            ;;
    esac

    # Begin real processing below this line

    modprobe rapiddisk
    modprobe rapiddisk-cache
    rapiddisk --attach 300
    rapiddisk --cache-map rd0 /dev/sda3 wa
    
    exit 0

Where  **`/dev/sda3`** is the root partition of my system.

This commands are executed during boot, and **BEFORE** **`/dev/sda3`** is mounted as `/`.

Now we need to update the initrfs with `update-initrtfs -u`:

    shub@WarHP:~$ sudo update-initramfs -u
    [sudo] password for shub:
    update-initramfs: Generating /boot/initrd.img-5.4.0-31-generic
    shub@WarHP:~$ lsinitramfs /boot/initrd.img-5.4.0-31-generic | grep -i rapiddisk
    scripts/init-premount/rapiddisk
    usr/lib/modules/5.4.0-31-generic/updates/dkms/rapiddisk-cache.ko
    usr/lib/modules/5.4.0-31-generic/updates/dkms/rapiddisk.ko
    usr/sbin/rapiddisk
    shub@WarHP:~$

At the end of the boot, we will find:

    shub@WarHP:~$ mount | grep mapper
    /dev/mapper/rc-wa_sda3 on / type btrfs (rw,relatime,space_cache,subvolid=257,subvol=/@)
    /dev/mapper/rc-wa_sda3 on /home type btrfs (rw,relatime,space_cache,subvolid=258,subvol=/@home)
    shub@WarHP:~$

My biggest doubt is about the need of modifying `/etc/fstab` to reflect the new situation.

Fllowing this procedure step by step while writing this post under `Ubuntu 20.04 LTS` I DID NOT changed it, and automagically the system mounted the mapped devs instead of the `/dev/sda3` ones.

I believe this is because I refer to partition by UUIDs in `/etc/fstab`:

    # /etc/fstab: static file system information.
    #
    # Use 'blkid' to print the universally unique identifier for a
    # device; this may be used with UUID= as a more robust way to name devices
    # that works even if disks are added and removed. See fstab(5).
    #
    # <file system> <mount point>   <type>  <options>       <dump>  <pass>
    # / was on /dev/sda3 during installation
    UUID=81743e75-cdb5-4261-9220-aca9e76c0ded       /               btrfs           defaults,compress=no,datasum,subvol=@           01
    # /home was on /dev/sda3 during installation
    UUID=81743e75-cdb5-4261-9220-aca9e76c0ded       /home           btrfs           defaults,compress=no,datasum,subvol=@home       02
    UUID=16a4d216-e099-4ade-a219-7c376632781c       /boot           ext2            defaults        0       2

`blkid` output:

    shub@WarHP:~$ sudo blkid
    /dev/sda1: LABEL="Keeper" UUID="6CD0EB53D0EB21D6" TYPE="ntfs" PARTUUID="60325519-01"
    /dev/sda2: LABEL="Linux-Boot" UUID="16a4d216-e099-4ade-a219-7c376632781c" TYPE="ext2" PARTUUID="60325519-02"
    /dev/sda3: UUID="81743e75-cdb5-4261-9220-aca9e76c0ded" UUID_SUB="dfd01a8d-f427-4bde-aa82-e367dacf234c" TYPE="btrfs" PARTUUID="60325519-03"
    /dev/mapper/rc-wa_sda3: UUID="81743e75-cdb5-4261-9220-aca9e76c0ded" UUID_SUB="dfd01a8d-f427-4bde-aa82-e367dacf234c" TYPE="btrfs"
    shub@WarHP:~$

One side effect seems to be you can revert to pre-Rapiddisk situation just commenting out the commands from the `initramfs boot script`. On the other hand, if you refer to partition by the `/dev/xxx` notation inside `fstab`, the mapped devices will still be created but not be used and this may lead to a non-booting system...

Note: on ubuntu there is an equivalent of the `/usr/share/initramfs-tools` dir structure in `/etc/initramfs-tools`. I suppose it should be used instead of putting new files in the `/usr/share/` dir tree.

If someone can try this out I can begin to think of a way to add the scripts to the tree.

Bye!
[rapiddisk_initrd_scripts.tar.gz](https://github.com/pkoutoupis/rapiddisk/files/4652604/rapiddisk_initrd_scripts.tar.gz)

**Comment by pkoutoupis** [comment]
Refer to @Shub77's PR #43 for work on this.

**Comment by pkoutoupis** [comment]
Integrated in the the latest mainline version 6.1: https://github.com/pkoutoupis/rapiddisk/releases/tag/6.1
