### ISSUE TITLE
Question: Read-ahead Cache

### ISSUE THREAD

**Issue by msmith626** [pkoutoupis/rapiddisk#39]
Hi,

Thank you for this great project! I've glanced at the kernel module sources and user-land utility, but it's not clear to me that this read cache is doing read-ahead -- is that accurate? If it does in fact do read-ahead of the source/backing device, how do you adjust the amount of read-ahead?

Thanks for your time.

--Marc

**Comment by pkoutoupis** [comment]
Marc, hello!

You are very welcome and thank you very much for your interest. Sadly, the project does not support read-ahead. Only write-through and write-around are supported. I did however discover a misleading comment in the module/rapiddisk-cache.c file which states that it does. I corrected this in commit 246ac4df1d6c4c6e063f4ea79e9ffa2c433e8e86.

**Comment by msmith626** [comment]
Understood, thanks for the quick reply.

**Comment by pkoutoupis** [comment]
Not a problem. Now, I don't really tamper with the parameter but you can modify a device's read ahead value under `sysfs`:

```
$ cat /sys/block/sdc/queue/read_ahead_kb
128
```

Its permissions are 644 for `root` and you should be able to `echo` a new value, should you choose to do so. Anyway, best of luck!
