### ISSUE TITLE
O_DIRECT Support?

### ISSUE THREAD

**Issue by msmith626** [pkoutoupis/rapiddisk#40]
Hi,

Any plans or perhaps an implementation is already underway for O_DIRECT (direct I/O) support? When attempting to use this feature with 'fio' we of course get a failure:
fio: looks like your file system does not support direct=1/buffered=0
fio: destination does not support O_DIRECT

Thanks,

Marc

**Comment by msmith626** [comment]
@pkoutoupis Please disregard, I was specifying /dev/rc-wt_sdb instead of /dev/mapper/rc-wt_sdb so that was my bad! Closing...

**Comment by pkoutoupis** [comment]
No worries. If you ever hit another issue, please do not hesitate to reach out and/or open up a new ticket.
