### ISSUE TITLE
Kernel modules do not automatically rebuild during system update on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by bberberov** [pkoutoupis/rapiddisk#5]
Kernel modules do not automatically rebuild during system updates on OpenSUSE Tumbleweed.

```
> uname -sr 
Linux 4.7.6-1-default
```

```
> dkms status
rapiddisk, 4.3, 4.7.4-2-default, x86_64: installed
rapiddisk, 4.3, 4.7.5-1-default, x86_64: installed
```

**Comment by pkoutoupis** [comment]
I will investigate, thank you.

**Comment by pkoutoupis** [comment]
Can you please retest the DKMS build with 4.4?

**Comment by bberberov** [comment]
Just did an upgrade to module 4.4.  The module built, but my backup kernel modules were removed.  If I had to boot to an older kernel for some reason, `rapiddisk` would be unavailable.  OpenSUSE keeps at least 1 backup.

I'll wait for the next kernel update and see what happens.

**Comment by pkoutoupis** [comment]
I completely understand where you are coming from but this is a tough one. The %preun of the spec file [completely] removes all instances of the old version of the module, and the %postun makes sure it is all cleaned up.

Now on an updated install, you should definitely see a fresh build of the latest (via %post). And all following kernel updates will trigger this as well.

The idea is, if you remove the RPM, you would want to make sure all traces of the outdated module are accounted for. Part of the yum update process will remove the old RPM triggering this.

Now, in theory....i can modify the dkms remove to ONLY remove the current kernel's module build and make sure to remove the cleanup in the %postun. But I am not sure how I feel about this. Again, this does not clean up every trace on the removal of the RPM.

Thoughts?

**Comment by bberberov** [comment]
I think we should figure out how to package RapidDisk "the OpenSUSE way".  Although both OpenSUSE and RHEL/Fedora are RPM based, they are different.  I don't know much about RPM, but I think the spec file needs to generate multiple packages.  At least one for the userspace tools and one for the kernel modules.  The modules one needs to integrate with OpenSUSE and their built-in management of out-of-tree modules.

I'll try to figure this out, but it might take a while.

Meanwhile, reinstalling the RapidDisk package on a kernel update will work fine.

**Comment by pkoutoupis** [comment]
If you do not mind. I will close this ticket, since the original issues has since been resolved. And I would request that you open an enhancement ticket to cover the potential update to auto module builds.

**Comment by bberberov** [comment]
I cannot seem to tag it as "Enhancement".  Must me a permissions thing in GitHub.
