### ISSUE TITLE
Where to see information about how start rapiddisk module in system start ?

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#57]
Rapiddisk service is installed and starting in each system start.
command below works
sudo rapiddisk -a 128

but when trying to map and partition the command below not work
sudo rapiddisk -m rd0 -b /dev/sda2
/dev/sda2 is currently mounted. Please "umount" and retry.

sda2 and sda 3 are 2 partitions on disk that I want to use rapiddisk cache.
look how if the command need to be done in system startup before OS mount each partition.

Rapiddisk not has command to enable load rapiddisk module and create an ramdisk device map to disk partition ?

Thanks for reply.

**Comment by pkoutoupis** [comment]
@Augusto7743: 

The rapiddiskd daemon is intended to provide an API for external (and network) management. The full API is document both in the [source](https://github.com/pkoutoupis/rapiddisk/blob/master/doc/API.txt) and in the [wiki](https://github.com/pkoutoupis/rapiddisk/wiki/The-RESTful-API). That way, an external management system can manage the RAM drives and cache mappings across multiple servers.

As for enabling rapiddisk-cache on system bootup, @Shub77 did a wonderful thing and provided script files to do just that. They are located here in the source tree: https://github.com/pkoutoupis/rapiddisk/tree/master/misc/rapiddisk-rootdev. PLEASE read the README.md first and exercise this in a VM before running it on a physical system. If you find a bug with it, be sure to either update this ticket or file a new one.

**Comment by pkoutoupis** [comment]
I will be closing this ticket as there is already a published process to enable RapidDisk at system boot up (see comment above).
