### ISSUE TITLE
Does RapidDisk prevent writing past the end of the RamDisk?

### ISSUE THREAD

**Issue by rjt** [pkoutoupis/rapiddisk#6]
Seems that by default, one can write much more to a traditional Linux RamDisk than what is allocated to it.  IE:  One can write 4GB of data to a 1MB RamDisk.  No errors seem to be generated until many times the size of the RamDisk is written.  Does RapidDisk solve that?

[low network performance between Citrix XenServer and Linux iSCSI storage](https://serverfault.com/questions/806496/low-network-performance-between-citrix-xenserver-and-linux-iscsi-storage/810864#810864)

**Comment by pkoutoupis** [comment]
Like any other block device in the kernel, RapidDisk assumes a fixed [virtual] sector count. If you application attempts to seek or read/write beyond the last sector, the kernel will return an ENOSPC or "no more space left on the device." So, to answer your question directly: Yes, RapidDisk does solve that.

It is also worth noting that RAM is consumed as it is used. What I mean is, if you allocate 4GB for a RAM drive but only write to 1.5GB, then only 1.5GB of system memory is being used by the RapidDisk volume.
