### ISSUE TITLE
the log message "signature and/or required key missing - tainting kernel" is related to any problem ?

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#60]
When starting with rapiddisk installed and configured to load modules in startup is displayed the log lines below

[    8.918580] systemd[1]: Configuration file /etc/systemd/system/rapiddiskd.service is marked executable. Please remove executable permission bits. Proceeding anyway.
[    9.910348] kernel: rapiddisk: loading out-of-tree module taints kernel.
[    9.914160] kernel: rapiddisk: module verification failed: signature and/or required key missing - tainting kernel

The messages above are to be ignored ? the module is loading correctly ?
Trying understand how configure to enable rapiddisk in partition root and home in system startup.

Thanks for reply.

**Comment by pkoutoupis** [comment]
Modern distributions build their kernels to sign all in-tree modules that were built during compilation. Seeing how this is an out-of-tree module and not signed by the same or similar process, the kernel will issue the above warning. Nothing changes in terms of kernel (or module) functionality as a result. This is nothing to be concerned about.

As for enabling rapiddisk-cache on system bootup, @Shub77 did a wonderful thing and provided script files to do just that. They are located here in the source tree: https://github.com/pkoutoupis/rapiddisk/tree/master/misc/rapiddisk-rootdev. PLEASE read the README.md first and exercise this in a VM before running it on a physical system. If you find a bug with it, be sure to either update this ticket or file a new one.

**Comment by Augusto7743** [comment]
in other words I only need ignore because all is working correctly ?
Have an nice day.

**Comment by pkoutoupis** [comment]
Correct. :-)
