### ISSUE TITLE
Write-Back is lacking statistics 

### ISSUE THREAD

**Issue by Chrisputer** [pkoutoupis/rapiddisk#65]
I have write-back setup on sda3 but there is not info about how it's performing OR its not descriptive enough.
**Side Note:** I see as of 6.1 some scripts where used to initialize Rapiddisk at boot for root, but I cannot find documentation on how to do that.

`[root@ovirt-nfs ~]# curl -s --output - 127.0.0.1:9118/v1/showRapidDiskCacheStats/rc-wb_sda3|tail -n1|jq
[root@ovirt-nfs ~]# rapiddisk -l
rapiddisk 7.2.1
Copyright 2011 - 2021 Petros Koutoupis

List of RapidDisk device(s):

 RapidDisk Device 1: rd0        Size (KB): 33554432

List of RapidDisk-Cache mapping(s):

 dm-writecache Target   1: rc-wb_sda3   Cache: rd0  Target: sda3 (WRITEBACK)

[root@ovirt-nfs ~]# rapiddisk -s rc-wb_sda3
rapiddisk 7.2.1
Copyright 2011 - 2021 Petros Koutoupis

0 7023880192 writecache 0 8355967 8355967 0
`

**Comment by pkoutoupis** [comment]
@Chrisputer:
Thank you for experimenting with my driver. There are a few things to comment on here so let me start with the simplest:

1. Re: docs on boot for root...
The README exists at this URL: https://github.com/pkoutoupis/rapiddisk/blob/master/misc/rapiddisk-rootdev/README.md. The author was pretty thorough but if you find that it is missing key components, please open up a new ticket against it. Also, exercise the instructions in a VM first before applying them on a production system.

2. Re: Write-back stats...
Unfortunately, I cannot address this as I did not write the device mapper module dm-writeback. As I state in the rapiddisk man page, the cli utility serves as a wrapper to the dm-writeback module. Although, I should probably place the same info in the cli menu. Anyway, I am looking through the dm-writeback code and there is no real way to pull up similar metrics to those found in my rapiddisk-cache module.

```
$ sudo dmsetup status /dev/mapper/rc-wb_sdd 
0 13672382464 writecache 0 65280 35840 0

$ sudo dmsetup table /dev/mapper/rc-wb_sdd 
0 13672382464 writecache s 8:48 252:0 4096 0

$ sudo dmsetup info /dev/mapper/rc-wb_sdd 
Name:              rc-wb_sdd
State:             ACTIVE
Read Ahead:        256
Tables present:    LIVE
Open count:        0
Event number:      0
Major, minor:      253, 0
Number of targets: 1
```

**Comment by pkoutoupis** [comment]
@Chrisputer : I am working on a branch that will enable more descriptive stats via JSON for dm-writecache but it is limited only to what the kernel module is outputting. For example:

```
{
  "statistics": [
    {
      "cache_stats": [
        {
          "device": "rc-wb_sdd",
          "errors": 0,
          "num_blocks": 16320,
          "num_free_blocks": 16320,
          "num_wb_blocks": 0
        }
      ]
    }
  ]
}
```
I will use this ticket to track the feature enhancement.

**Comment by pkoutoupis** [comment]
The latest release 8.0.0 (and current master) has this JSON output implemented. Closing the ticket.
