### ISSUE TITLE
WSL2 rapiddisk-cache unlimited memory growth

### ISSUE THREAD

**Issue by w0lv3r1nix** [pkoutoupis/rapiddisk#66]
Hi Petros,

I've managed to install rapiddisk on wsl2 running Ubuntu 2004.
The problem is when I create a cache for a disk and start writing to it, the memory start to growth and never stops.

`rapiddisk -a 64`
`rapiddisk -m rd0 -b /dev/sdb1`
`mount /dev/mapper/rc-wt_sdb1 /mnt/rc-wt_sdb1/`
`dd if=/dev/zero of=tt2.img bs=1000M count=1000`

```
My c:\Users\<user>\.wslconfig

[wsl2]
memory=30G
processors=22
```

![image](https://user-images.githubusercontent.com/5229665/129808837-a1fc5184-f056-4397-ab36-5911c041c4a4.png)

You can replicate it, using the following steps:
```
git clone https://github.com/pkoutoupis/rapiddisk

--Because I'm using the kernel 5.10
git clone https://github.com/microsoft/WSL2-Linux-Kernel.git -b linux-msft-wsl-5.10.y

--If someone wants to download other kernels 
https://www.catalog.update.microsoft.com/Search.aspx?q=wsl

--create vhdx  to test it
--mount vhdx as physical disk (Windows)
PS> Write-Output "\\.\PhysicalDrive$((Mount-VHD -Path ./external.vhdx -PassThru | Get-Disk).Number)"
--mount physical disk to wsl (aka. vhdx)
wsl --mount \\.\PhysicalDrive7 --bare

--created a partition on it 

cd WSL2-Linux-Kernel
cp ./Microsoft/config-wsl .config
--This is needed because wsl2 doesn't have modules on it
make modules_install

cd rapiddisk
make install
make tools-install

modprobe rapiddisk
modprobe rapiddisk-cache

rapiddisk -a 64
rapiddisk -m rd0 -b /dev/sdb1
--rapiddisk doesn't know the cache because it search for it on /dev/mapper and wsl2 doesn't have dm_multipath enabled
--a little trick
ln -s /dev/dm-0 /dev/mapper/rc-wt_sdb1 
mkdir /mnt/rc-wt_sdb1/
mount /dev/mapper/rc-wt_sdb1 /mnt/rc-wt_sdb1/
dd if=/dev/zero of=tt2.img bs=1000M count=1000
```

I'm not sure if it's something that worth digging into it, but I can help you troubleshooting if you need.

Thanks a lot, and keep up with the great work.

**Comment by pkoutoupis** [comment]
Hello @w0lv3r1nix, thank you for your interest in my project. I find it fascinating that you are attempting to get this to work in WSL2 although, I personally do not have any access to such an environment, so you will need to help fill in some gaps. For instance...

> --rapiddisk doesn't know the cache because it search for it on /dev/mapper and wsl2 doesn't have dm_multipath enabled

Did you mean dm_multipath or device-mapper as a whole? RapidDisk-Cache does not make use of dm_multipath but it **does** rely on the device-mapper framework. Without it, it cannot function properly.

**Comment by w0lv3r1nix** [comment]
Hi @pkoutoupis 
Yeah, it was a crazy idea, I've notice that wsl2 has better IO performance than win10/11 and I was using primocache on windows, so I decided to try to recreate that on wsl2.

I think device-mapper is ok and running, I can see the device created by rapiddisk on /dev/dm-0 and I can check that with dmsetup status, but the device is not mapped on /dev/mapper and I think rapiddisk is looking for it.

**Comment by pkoutoupis** [comment]
Does a normal rapiddisk ram drive work? For instance, if you create rd0 (of a size oof 256 MB) and write to it with dd. Does it stop at 256 MB and does the system's memory footprint reflect that? I want to see if we can narrow this down to just the caching component or device mapper.

**Comment by w0lv3r1nix** [comment]
Yes
```
rapiddisk -a 500
mount /dev/rd0 /mnt/ramdisk/
dd if=/dev/zero of=test.img bs=1M count=5000
dd: error writing 'test.img': No space left on device
484+0 records in
483+0 records out
506941440 bytes (507 MB, 483 MiB) copied, 0.342929 s, 1.5 GB/s
```

I did more research on this and found some interesting things.

1. I think wsl was not reclaiming the cache
    [Memory Reclaim in the WSL2](https://devblogs.microsoft.com/commandline/memory-reclaim-in-the-windows-subsystem-for-linux-2/)
    So using a while true with `echo 1 > /proc/sys/vm/drop_caches` I've managed to prevent the memory from blowing out.

2. The lvm2 that is inside ubuntu-20.04 has bug:
   [LVM2 writecache ](https://bugs.launchpad.net/ubuntu/+source/lvm2/+bug/1868129)
   So while I was recompiling it from source, I've managed to fix the issue with /dev/mapper/ not showing the rapiddisk cache drive.
   And I also think that this fixed the issue with unlimited grow.

3. After fixing lvm and the memory issue, I couldn't use the -p wb on rapiddisk, so I looked into the source and I found that you are looking for  dm_writecahe on the loaded modules, but mine was compiled inside the kernel (modules.builtin) so as a suggestion I think you should look for the module name inside the sys directory: /sys/module/<module>


Right now everything is "working" but when I start writing after a while my process get killed and I'm trying to figure out why, It's been quite a journy

**Comment by pkoutoupis** [comment]
> I think you should look for the module name inside the sys directory: /sys/module/

That is a great idea. And thank you for looking into this.

> I'm sorry I'm kind of beginner on this topic, can you show me how to create a block device using ram so I can troubleshoot that with native lvm to see if I have the same problem.

RapidDisk RAM block device or native kernel ram block device? You have already been creating it with RapidDisk but the brd native kernel module, to create a single 32 GB (for example) ram drive:

```
# modprobe brd rd_size=33554432 rd_nr=1
# pvcreate /dev/ram0
# vgcreate test-vg /dev/ram0
# lvcreate --name test-lv test-vg --size=32G
```

**Comment by w0lv3r1nix** [comment]
It works using rapiddisk but can't create vg on it because some filters.
and I don't know why, but brd doesnt let me create a big file:`
```
modprobe brd rd_size=33554432 rd_nr=1
pvcreate /dev/ram0
  allocation/use_blkid_wiping=1 configuration setting is set while LVM is not compiled with blkid wiping support.
  Falling back to native LVM signature detection.
  Physical volume "/dev/ram0" successfully created.
pvs
  PV         VG Fmt  Attr PSize  PFree
  /dev/ram0     lvm2 ---  64.00m 64.00m

**Comment by pkoutoupis** [comment]
Does this help?
[https://github.com/pkoutoupis/rapiddisk/wiki/Frequently-Asked-Questions-(FAQ)#lvm2-a-pvcreate-of-a-rapiddisk-volume-returns-with-a-volume-not-found-error](https://github.com/pkoutoupis/rapiddisk/wiki/Frequently-Asked-Questions-(FAQ)#lvm2-a-pvcreate-of-a-rapiddisk-volume-returns-with-a-volume-not-found-error)

```
LVM2: A pvcreate of a RapidDisk volume returns with a “volume not found” error.
In your /etc/lvm/lvm.conf file do a global search for “types =” and add the following line:

types = [ "rd", 1 ]

Then retry the pvcreate command.
```

**Comment by w0lv3r1nix** [comment]
No luck with lvm.conf:
```pvcreate /dev/rd0
 Cannot use /dev/rd0: device type is unknown

----
Processing data from device /dev/rd0 251:0 di 1 block 0x55f16825b400
  /dev/rd0: Skipping: Unrecognised LVM device type 251
  filter caching bad /dev/rd0
  Scanned devices: read errors 0 process errors 0 failed 0
  /dev/rd0: filter cache skipping (cached bad)
  Cannot use /dev/rd0: device type is unknown
  No devices to process.
  Unlocking /run/lock/lvm/P_global
  _undo_flock /run/lock/lvm/P_global
  Destroy lvmcache content
  Completed: pvcreate /dev/rd0 -vvv
---
```
I had to make brd external module so I finally can create ramdisk using it 😃

**Comment by pkoutoupis** [comment]
@w0lv3r1nix I dug deeper into the LVM2 user space source code and figured out why the RAM disk portion of the RapidDisk module suite is not able to be managed via the volume manager. LVM2 looks to see if the block device is supported and it determines support on whether the block devices can be physically partitioned. This code can be found in `lib/filters/filter-type.c` and specifically in the function `_passes_lvm_type_device_filter`.

Since the very beginning of RapidDisk, I had disabled partitioning (via fdisk/sfdisk/parted). It never made much sense to me to partition a dynamically created RAM drive when you can just create a new one at any time. It also simplified the management of minor numbers. This function will not be changing anytime in the near future.

Now, what does this mean? You are unable to use rapiddisk volumes in LVM2 **BUT** you are still able to use rapiddisk-cache volumes in the volume manager.

Seeing how your WSL2 issue has been addressed and we have gotten to the root of the LVM2 issue, I will close this ticket and if it continues to be an issue, we can always reopen or open a new ticket.
