### ISSUE TITLE
How enable rapiddisk to system start with writeback ?

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#67]
I have installed correctly Rapiddisk and see that in rapiddisk source file has 2 folders with scripts
/rapiddisk-7.2.0/misc/rapiddisk-legacy/
/rapiddisk-7.2.0/misc/rapiddisk-rootdev/

trying use the install_initrd.sh and return with errors even using 
sudo install_initrd.sh -- install --kernel_5.11.0-16-generic

I want enable rapiddisk to create a 64 MB ram buffer for /home with writeback enabled.
Recent version was added writeback.
Need configure any OS component (dm-write) before any command above ?

Testing using Oracle VirtualBox before install and enable in current systems (Ubuntu 20.04.3 and 21.04 both kernel 5.11)
Thanks very much for your reply.

**Comment by pkoutoupis** [comment]
@Augusto7743 It appears that you have not specified all of the necessary command line options such as "size": sudo ./install_initrd.sh --install --root=<root_partition> --size=<ramdisk_size> --kernel=<kernel_version>

Anyway, what is the error message that you are seeing?

**Comment by Augusto7743** [comment]
Hello pkoutoupis. Thanks very much for your reply and also for creating that amazing cache utility.

Using the command above now works.
after all completed was displayed
"done under Ubuntu. a reboot is required"

Thus was restarted the OS.
in OS start boot log is displayed

kernel:rapiddisk : "loading out-of-tree module taints kernel"
kernel:rapiddisk : module verification failed: signature and / or required key missing - taiting kernel
kernel rapiddisk : Attached rd0 of 6710864 files in size

Look being normal , but after add rapiddisk and rapiddisk-cache in /etc/modules is displayed

Error. Source device does not seem to be a normal block device listed in /dev directory path
Not need add rapiddisk in /etc/modules ?

**Comment by pkoutoupis** [comment]
This is expected because it is an out-of-tree module:
```
kernel:rapiddisk : "loading out-of-tree module taints kernel"
kernel:rapiddisk : module verification failed: signature and / or required key missing - taiting kernel
kernel rapiddisk : Attached rd0 of 6710864 files in size
```

As for this:
```
Error. Source device does not seem to be a normal block device listed in /dev directory path
```
What is the exact command that you are executing or the block device you are using?

**Comment by Augusto7743** [comment]
I had tried to install rapiddisk using a folder using long name with spaces.
Thus I had moved to /home/rapiddisk and run the command

sudo ./install_initrd.sh --install --root=/dev/sda6 --size=256 --kernel=5.11.0-27-generic --force

finally was installed

After I had done
sudo nano /etc/modules

adding

rapiddisk
rapiddisk-cache
dm-writecache

OS started and rapiddisk service is running
doing the command
sudo rapiddisk -m rd0 -b /dev/sda6 -p wb

"Error. At least one of your cache/source devices is currently mapped to rc-wa_sda6."

Look not being a error and using write around,

I had done the command "sudo rapiddisk -m rd0 -b /dev/sda6 -p wb" waiting enable the writeback mode , but the message display that is being mapped.


What exact command to enable writeback to "rd0 rc-wa_sda6" ?
Need to be done in initramfs ? If yes need change the install_initrd.sh.

I want to create cache for 2 partitions. Trying run 2 times "install_initrd.sh" changing the mount point in command line waiting thus create cache for 2 partitions look how if only one partition will be used and was changed the selected partition (from sda3 to sda6 in second command done).

I have tested in Ubuntu 20.04.3 and 21.04 installing rapiddisk using install_initrd.sh and works.
I only need understand what command to enable writeback (if possible configure a delay time defer write) ,if is possible create 2 ramdisk caches for 2 partitions and if using writeback mode also have the same feature file cache when using write-through.

Have a nice day.

**Comment by pkoutoupis** [comment]
@Augusto7743 A couple of things going on here:

1. I am looking through the rootdev scripts and it does not support writeback caching and honestly, I personally do not believe that it should only because of how volatile memory is. To enable this on a root device could potentially be disastrous for the OS.
2. You are rerunning the rapiddisk command (after boot time and after the write-around cache has been enabled). That is why you are seeing the error that you are seeing.

**Comment by Augusto7743** [comment]
I need again say thanks very much for your software.

I understand your good act saying about caution enabling writeback. Here has eletric protection.
I had used another OS with writeback for a long time without issues. The writeback was to partition used by browsers thus had avoided extreme repeated writing created by browsers. Even disabling temporary files the browsers use writing data for others tasks. In few hours using are more than 2 GB in data that will be deleted.
Writeback is good for SSD.

Thus in Linux the browsers use very much /home.

I have edited the rootdev script and enabled writeback , but the command need before load dm-writecache.
I want to enable 2 ramdisk for writeback for /home and another partition with data being mounted in OS boot.
I not see in moment how create 2 ramdisks. The script only allow one ramdisk.
I will try edit rootdev script and and test if is or not possible add 2 ramdisks.

**Comment by pkoutoupis** [comment]
@Augusto7743 Can you please share (maybe a git diff) of what changes you have made for future users here in this ticket? While I personally feel that it should not be included in the mainline (for data integrity reasons), I can redirect users to this ticket number and/or post it in the project's Wiki / FAQ.

**Comment by Augusto7743** [comment]
Thanks very much for your reply and help me.

I had edited rapiddisk_sub.orig and changed
rapiddisk -m rd0 -b BOOTDEVICE -p wa
to
rapiddisk -m rd0 -b BOOTDEVICE -p wb

When OS start boot is displayed a message about not being possible run rapiddisk command. Is because dm-writeback not was loaded.
I am new Linux user thus not being possible in moment enable dm-writeback and configure defer delay for write.

I never had used a cache utility with read cache how rapiddisk does.
Writeback and write-around are good and speed up the OS.

I will try edit the script and try see if is possible create 2 ramdisk caches and also if is possible copy dm-writeback module in initramfs.

**Comment by pkoutoupis** [comment]
I have added a link to the above post in the project Wiki and at the bottom of the FAQ: https://github.com/pkoutoupis/rapiddisk/wiki/Frequently-Asked-Questions-(FAQ).
