### ISSUE TITLE
What is the means "RapidDisk-Cache Mappings statistics" ?

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#72]
Running
sudo rapiddisk -s /dev/mapper/rc-wb_sdaX
Is displayed
rapiddisk 7.2.1
0 25165824 writecache 0 32640 17184 0

What is the information in each number group ?
Thanks for reply.

**Comment by pkoutoupis** [comment]
This is what the kernel documentation says: https://www.kernel.org/doc/html/latest/admin-guide/device-mapper/writecache.html
```
Status:
1. error indicator - 0 if there was no error, otherwise error number
2. the number of blocks
3. the number of free blocks
4. the number of blocks under writeback
```

In my https://github.com/pkoutoupis/rapiddisk/tree/feature/nvme-export-support branch, I make this a bit more clear over the REST API:

```
{
  "statistics": [
    {
      "cache_stats": [
        {
          "device": "rc-wb_sdd",
          "errors": 0,
          "num_blocks": 16320,
          "num_free_blocks": 16320,
          "num_wb_blocks": 0
        }
      ]
    }
  ]
}
```


**Note** the latest versions of dm-writecache has more fields which I do not account for in my code (yet).
```
Status:
1. error indicator - 0 if there was no error, otherwise error number
2. the number of blocks
3. the number of free blocks
4. the number of blocks under writeback
5. the number of read requests
6. the number of read requests that hit the cache
7. the number of write requests
8. the number of write requests that hit uncommitted block
9. the number of write requests that hit committed block
10. the number of write requests that bypass the cache
11. the number of write requests that are allocated in the cache
12. the number of write requests that are blocked on the freelist
13. the number of flush requests
14. the number of discard requests
```

**Comment by Augusto7743** [comment]
Thanks.

**Comment by pkoutoupis** [comment]
@Augusto7743 Hello. Can we close this or do we need to redefine the issue?

**Comment by Augusto7743** [comment]
Is good see in RapidDisk CLI the total written done for each writeback cache.
When the cache if full is done written in disk.

**Comment by pkoutoupis** [comment]
I added support for these extended statistics in dm-writecache which appear in the 5.15 kernel and later in the latest release 8.1.0: https://github.com/pkoutoupis/rapiddisk/releases/tag/8.1.0
As before, they are more description in the JSON implementation via the daemon. Please refer to the doc/API.txt for additional information on extracting this data from dm-writecache.

**Comment by Augusto7743** [comment]
Here using 5.11, but thanks very much for add that feature.
Thanks very much for your amazing software.
Have an nice week.
