### ISSUE TITLE
Raid 0 supported ?

### ISSUE THREAD

**Issue by m0hamedessam** [pkoutoupis/rapiddisk#80]
Hello,

Im using 12x 18TB SATA raid 0 and im wondering to use rapiddisk to increase performance because i have already 128G ram but i have some questions.

**Is it support raid0 ?**

**i dont want lose any data so i can ram drive without any formatting ??**

https://delightlylinux.wordpress.com/2017/02/15/rapiddisk-improved-hard-drive-caching/
because regarding tutorial above drive need to be formatted
**sudo mkfs.ext4 /dev/rd0**

So any advice how to use it without lose any data ??

**Comment by pkoutoupis** [comment]
@m0hamedessam, yes, adding RapidDisk as a cache to a pre-existing RAID **is** supported. You do not need to reformat anything and the attaching/removal of the cache is non-destructive **only** if you use a write-around or write-through caching policy. I have clear instructions on how to configure this in the project wiki here: https://github.com/pkoutoupis/rapiddisk/wiki/RapidDisk-Administration-Utility

You will first need to specify a RapidDisk RAM drive of whatever size you need (you do not need to format this RAM drive). Then, you will need to make sure that the RAID 0 is not mounted, map the RAM drive to the RAID 0 volume and then mount the new mapping.

Create a 32 GB RAM drive:
```
$ sudo rapiddisk -a 32768
```
Map the RAM drive to the RAID drive (with a write-around policy):
```
$  sudo rapiddisk -m rd0 -b /dev/md0 -p wa
```
Mount the cache-enabled RAID volume:
```
$ sudo mount /dev/mapper/rc-wa_md0 /mnt/rc-wa_md0
```

To remove the mapping, you will need to unmount the volume and then run the unmap option via the utility (-u).

**Comment by m0hamedessam** [comment]
Thanks for your answer but raid0 its hardware hp smart array (/dev/sda3) is already mounted and system running (ubuntu 18) how to go around that ?? Or can i cache only 2 folders which contains media which i want mainly cache ??

thanks in advance

**Comment by pkoutoupis** [comment]
Is /dev/sda3 part of your root image? If so, there is a set of scripts to enable RapidDisk on those volumes here: https://github.com/pkoutoupis/rapiddisk/tree/master/scripts/rapiddisk-rootdev. I would advise running it in a VM first before executing it on your actual machine.

**Comment by m0hamedessam** [comment]
Thanks for your fast response and as you recommend I will try it on test server first however im thinking to reinstall system on ssd hard disk and mount raid using cache instead of using it on root because im afraid to lose data just in case.

what you recommend is worth it or will be same performance just not buy ssd disk for system for no reason ??

**Comment by pkoutoupis** [comment]
The modules are primarily designed to increase read throughput. SSDs will cover the write piece of it. So, if write is what you are concerned with, then this module may not be the right fit for what you are trying to configure. If you intend on doing more read and require a large read cache, then yes, the module will be a perfect fit.

**Comment by m0hamedessam** [comment]
My concern for more read cache not write so thanks for your kindly answer and i will try on test server and let you know results.

Cheers..

**Comment by m0hamedessam** [comment]
hello im trying to compile and install module but before install root script im trying auto load module on boot but i couldn't due sign problem.

[    5.043381] rapiddisk_cache: loading out-of-tree module taints kernel.
[    5.043432] rapiddisk_cache: module verification failed: signature and/or required key missing - tainting kernel

I tried to manually sign modules but not help.

./scripts/sign-file sha512 ./certs/signing_key.pem ./certs/signing_key.x509 /lib/modules/4.15.0-166-generic/updates/dkms/rapiddisk.ko
./scripts/sign-file sha512 ./certs/signing_key.pem ./certs/signing_key.x509 /lib/modules/4.15.0-166-generic/updates/dkms/rapiddisk-cache.ko

So any idea how to solve this problem ?

**Comment by pkoutoupis** [comment]
I am not exactly sure. If manually signing it does not resolve it, I wonder how against you may be disabling the check for signed modules at boot up. You would need to set module.sig_enforce=0 as a kernel boot parameter in your grub.conf.

**Comment by m0hamedessam** [comment]
I tried set module.sig_enforce=0 but still same error.

any other idea ?

**Comment by pkoutoupis** [comment]
If you signing the modules or setting sig_enforce to 0 does not address the problem, then I wonder if the modules being certified is the problem. What other messages/errors are you seeing in dmesg during boot-up?

**Comment by m0hamedessam** [comment]
Only this on dmesg log 

[    7.118962] rapiddisk_cache: loading out-of-tree module taints kernel.
[    7.119018] rapiddisk_cache: module verification failed: signature and/or required key missing- tainting kernel

**Comment by m0hamedessam** [comment]
Any updates how properly sign module or properly disable sign from kernel???

**Comment by m0hamedessam** [comment]
Ubuntu 18.04

i tried everything to disable signing but noway unless mabe to compile new kernel with config signing disabled so i decided to try to sign module and main problem now trying to add key file i generate and sign module with to trusted system key becuase this the problem.

PKCS#7 signature not signed with a trusted key

i tried to add system kerying ID but permission denied 

keyctl padd asymmetric "" 0x0000000000 </usr/src/linux-headers-4.15.0-166/certs/signing_key.x509

do you have any clue to add key file to trusted kernel keys to fix this ??

**Comment by m0hamedessam** [comment]
finally after i re-compile kernel with disable module signing using this tutorial
https://discourse.ubuntu.com/t/how-to-compile-kernel-in-ubuntu-20-04/20268

Everything loaded and auto start good then i start root script

cd /root/rapiddisk/scripts/rapiddisk-rootdev
./install_initrd.sh --install --root=/dev/sda4 --size=16000 --kernel=`uname -r` --cache-mode=wa --force

and reboot but still after boot server theres no any disks attached

:~# rapiddisk -l
rapiddisk 8.1.0
Copyright 2011 - 2022 Petros Koutoupis
Unable to locate any RapidDisk devices.

~# lsinitramfs /boot/initrd.img-`uname -r` |grep -i rapidd
scripts/init-premount/rapiddisk_boot
sbin/rapiddisk
sbin/rapiddisk_sub
lib/modules/4.15.1/updates/dkms/rapiddisk.ko
lib/modules/4.15.1/updates/dkms/rapiddisk-cache.ko


what im missing here???

**Comment by pkoutoupis** [comment]
@matteotenca Any thoughts here?

**Comment by m0hamedessam** [comment]
yes its Ubuntu 18.04 and script run fine and all hooks file created normally and theres no any errors on dmesg or syslog

Even i tried to reinstall 

sudo apt remove initramfs-tools
sudo apt clean
sudo apt install initramfs-tools

and reboot but nothing....

is this script tested on ubuntu 18.04 ??

**Comment by matteotenca** [comment]
> @matteotenca Any thoughts here? This is on Ubuntu 18.04.
> 
> Also, @m0hamedessam, anything in dmesg? It looks as if you are running the script correctly.

To have a clear vision of what is happening, use the "debug" kernel parameter in `grub` config: during boot a verbose log regarding initramfs activities will be created in `/run/initramfs/initramfs.debug`.

**Comment by m0hamedessam** [comment]
@matteotenca 

https://we.tl/t-R1ncT3XfHo
files attached but i cant really see any errors

+ . /scripts/init-premount/ORDER
+ /scripts/init-premount/rapiddisk_boot
+ [ -e /conf/param.conf ]
+ [ n != y ]
+ log_end_msg
+ _log_msg done.\n
+ [ n = y ]
+ printf done.\n
done.

please check file and let me know whats problem ?

**Comment by matteotenca** [comment]
@m0hamedessam Give this branch a try: [https://github.com/matteotenca/rapiddisk/tree/ubuntu18](https://github.com/matteotenca/rapiddisk/tree/ubuntu18)

**Comment by matteotenca** [comment]
It is a really small change in one file:

```
Index: scripts/rapiddisk-rootdev/ubuntu/rapiddisk_boot
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/rapiddisk-rootdev/ubuntu/rapiddisk_boot b/scripts/rapiddisk-rootdev/ubuntu/rapiddisk_boot
--- a/scripts/rapiddisk-rootdev/ubuntu/rapiddisk_boot	(revision d4d849049e116da76024b0f76cbd50ecf3258fe9)
+++ b/scripts/rapiddisk-rootdev/ubuntu/rapiddisk_boot	(revision c53d62cc71ad5e8afbc1ededc048de7e955c6baf)
@@ -15,8 +15,8 @@
 . /scripts/functions
 
 # Begin real processing below this line
-if [ -x /usr/sbin/rapiddisk_sub ] ; then
-	/usr/sbin/rapiddisk_sub
+if [ -x /sbin/rapiddisk_sub ] ; then
+	/sbin/rapiddisk_sub
 fi
 
 exit 0

```

**Comment by m0hamedessam** [comment]
finally works @matteotenca thanks a lot after more than week :) but how can i properly test HDD read speed because i see no difference

**Comment by m0hamedessam** [comment]
@pkoutoupis any idea how properly test read cache speed ?

**Comment by pkoutoupis** [comment]
Remember, it is read cache and if the data isn't staged in memory, then it won't go to memory. This is even more the case when using a write-around policy. A method that comes to mind is to create temporary directory and using a benchmarking utility like fio, write a substantial amount of small files. Read them all once to see the uncached perf and have it get staged into memory and then read it a second time to see the cached performance. This may not be the best way to test on a root file system. I originally built and tested on raw block device intended to be exported on a network and my testing methods tend to differ.

**Comment by pkoutoupis** [comment]
@m0hamedessam, I wanted to follow up. Has this question or issue been settled. Were you able to determine if your workload improved with your setup? Again, it all depends on the profile of you workload. Either way, if this ticket has been resolved, I would like to propose that we close it.

**Comment by m0hamedessam** [comment]
You can close ticket everything is ok.
