### ISSUE TITLE
RapidDisk, does it comes configured?

### ISSUE THREAD

**Issue by Hyphaed** [pkoutoupis/rapiddisk#84]
Hi

I'm eager to use RapidDisk, I would like to know if comes pre-configured

If I install it from sources, and I install the DKMS module. Will it automatically cache temp data and most used app data on RAM?

I have 64Gb of RAM and I would like my system to use up to 32Gb to store all the data of most used programs

**Comment by pkoutoupis** [comment]
Hello and thank you for your interest. No, RapidDisk does not come preconfigured after installation. With the help of contributors, I have put together a Wiki for the project that will not only get you started but also learn more about advanced features and configuration: [https://github.com/pkoutoupis/rapiddisk/wiki](https://github.com/pkoutoupis/rapiddisk/wiki)

**Comment by pkoutoupis** [comment]
Hello @Hyphaed. Seeing how your question has been answered, I will close this ticket and if you have any new questions or come across new issues, feel free to open up a new one. Thank you.
