### ISSUE TITLE
install_initrd.sh not working in Ubuntu 20.04.3 with kernel update 5.17

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#85]
Hello.
I have installed Ubuntu 20.04.3 being kernel 5.11 and using install_initrd.sh works.
I have updated the kernel to 5.17.3-051703-generic.
When trying the command below

sudo bash install_initrd.sh --install --size=128 --cache-mode=wb --kernel=5.17.3-051703-generic
**** Error: the kernel version you specified is not installed. Exiting...

using uname -r
5.17.3-051703-generic

and using dpkg --list | grep linux-image

ii  linux-image-5.11.0-27-generic                 5.11.0-27.29~20.04.1                amd64        Signed kernel image generic
ii  linux-image-generic-hwe-20.04                 5.11.0.27.29~20.04.11               amd64        Generic Linux kernel image
ii  linux-image-unsigned-5.17.3-051703-generic    5.17.3-051703.202204140912          amd64        Linux kernel image for version 5.17.3 on 64 bit x86 SMP

another detail when OS starting have the message in boot process

"Failed to start A rapiddisk network management daemon"

I will try install the OS being 5.11 installing rapiddisk in dkms and after updating the kernel.
Thanks for read.

**Comment by pkoutoupis** [comment]
@Augusto7743 It is unclear to me whether you built and installed the package prior to using the script. Can you please very that being the case. Also, is this an Ubuntu provided kernel or is it from a third-party repo installation?

@matteotenca any thoughts?

**Comment by Augusto7743** [comment]
@pkoutoupis

Hello. All right with you ?
Thanks very much. Rapiddisk is an brilliant software.

I have used your software for more than one year and need say had happen problems possibly not related with your software.
The only problem is when using writeback in an btrfs parition if happen partial written without an metadata (metadata is the Linux naming for partition file table ?) flush in next OS start the btrfs partition is damaged at point not being possible fix it using default fix commands.
OS used was Ubuntu 20.04.3 kernel 5.11.
Thus how new kernel have fixes for btrfs I had updated the kernel to 5.17.3 using the PPA below
https://launchpad.net/~tuxinvader/+archive/ubuntu/lts-mainline
The kernel was installed correctly.

Rapiddisk is compiled and installed correctly.
When using the command below happen the error

sudo bash install_initrd.sh --install --size=128 --cache-mode=wb --kernel=5.17.3-051703-generic
**** Error: the kernel version you specified is not installed. Exiting...

The PPA creator has done an reply about it.
https://github.com/TuxInvader/focal-mainline-builder/issues/17

He say

"Please modify your install_initrd.sh script and change line 178
kernel_installed="$(dpkg-query --list | grep -P 'linux-image-\d' |grep '^.i'| awk '{ print $2 }'| sed 's,linux-image-,,')"

kernel_installed="$(dpkg-query --list | grep -P 'linux-image-(unsigned-)?\d' |grep '^.i'| awk '{ print $2 }'| sed -re 's,linux-image-(unsigned-)?,,')"

Currently the script does not support unsigned kernels, this change will make it detect both signed and unsigned.
If this works for you then you might want to request a change on the pkoutoupis/rapiddisk project."

Now the install_initrd.sh works and sudo rapiddisk -l show the writeback cache.

Is problem modify the original install_initrd.sh to allow install in unsigned kernels ? If yes not problem.

Kernel 5.17.3 have good improvements for BTRFS.
Thus I will test if not happen problems how was when using kernel 5.11.

Thanks very much for you with your talent and trying reply.

**Comment by pkoutoupis** [comment]
@matteotenca What are your thoughts on the proposed change?

```
"Please modify your install_initrd.sh script and change line 178
kernel_installed="$(dpkg-query --list | grep -P 'linux-image-\d' |grep '^.i'| awk '{ print $2 }'| sed 's,linux-image-,,')"

kernel_installed="$(dpkg-query --list | grep -P 'linux-image-(unsigned-)?\d' |grep '^.i'| awk '{ print $2 }'| sed -re 's,linux-image-(unsigned-)?,,')"

Currently the script does not support unsigned kernels, this change will make it detect both signed and unsigned.
If this works for you then you might want to request a change on the pkoutoupis/rapiddisk project."
```

**Comment by matteotenca** [comment]
> @Augusto7743
> 
> Thank you for doing your part and helping to find this and finding a potential resolution.
> 
> @matteotenca What are your thoughts on the proposed change?

I have a question: is it possible to install a signed and an unsigned kernel with the same version number at the same time, for example "linux-image-5.13.0-30-generic" and "linux-image-unsigned-5.13.0-30-generic"?

And is there a similar situation under CentOS (different kernel images with the same version number)?

Thanks!

**Comment by TuxInvader** [comment]
@matteotenca It isn't on Ubuntu. The signed and unsigned kernels conflict with one another.
```
$ apt-cache depends linux-image-unsigned-5.4.0-104-generic
  linux-image-unsigned-5.4.0-104-generic
    Depends: kmod
      kmod:i386
    Depends: linux-base
    Depends: linux-modules-5.4.0-104-generic
    Conflicts: linux-image-5.4.0-104-generic
    ...
    Suggests: linux-headers-5.4.0-104-generic
```
both the signed and unsigned kernels depend on the same modules and headers packages.

**Comment by matteotenca** [comment]
> @matteotenca It isn't on Ubuntu. The signed and unsigned kernels conflict with one another.
> 
> ```
> $ apt-cache depends linux-image-unsigned-5.4.0-104-generic
>   linux-image-unsigned-5.4.0-104-generic
>     Depends: kmod
>       kmod:i386
>     Depends: linux-base
>     Depends: linux-modules-5.4.0-104-generic
>     Conflicts: linux-image-5.4.0-104-generic
>     ...
>     Suggests: linux-headers-5.4.0-104-generic
> ```
> 
> both the signed and unsigned kernels depend on the same modules and headers packages.

Thanks, I made the proposed changes. I need to made some test under CentOS, now the installation process is the same as before.

**Comment by Augusto7743** [comment]
@TuxInvader
Thanks very much for your reply =)
