### ISSUE TITLE
Make Error Kubuntu 21.10

### ISSUE THREAD

**Issue by juanpc2018** [pkoutoupis/rapiddisk#95]
$ make
make -C src 
make[1]: Entering directory '/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/src'
Make has completed.
make[1]: Leaving directory '/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/src'

make -C conf 
make[1]: Entering directory '/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/conf'
Nothing to do.
make[1]: Leaving directory '/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/conf'

make -C doc 
make[1]: Entering directory '/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/doc'
Nothing to do.
make[1]: Leaving directory '/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/doc'

make -C module 
make[1]: Entering directory '/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/module'
make -C /lib/modules/5.13.0-41-generic/build M=/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/module
make[2]: Entering directory '/usr/src/linux-headers-5.13.0-41-generic'
make[2]: *** No rule to make target 'Rapidisc/rapiddisk-8.1.0/module'.  Stop.
make[2]: Leaving directory '/usr/src/linux-headers-5.13.0-41-generic'
make[1]: *** [Makefile:37: all] Error 2
make[1]: Leaving directory '/home/K/Downloads/Linux Rapidisc/rapiddisk-8.1.0/module'
make: *** [Makefile:26: module] Error 2

**Comment by matteotenca** [comment]
The path to the module source can't contain whitespaces. So you should change:

```
/home/K/Downloads/Linux Rapidisc
```

to something like:

```
/home/K/Downloads/Linux_Rapidisc
```

It's a `make` limit, see [HERE](https://unix.stackexchange.com/questions/448913/how-to-compile-linux-kernel-modules-within-white-space-separated-directories-und).

**Comment by pkoutoupis** [comment]
@juanpc2018 It is also unclear to me on whether you have the kernel source/headers installed on the distribution. You should make sure that the `linux-headers` package is installed for your running kernel.

**Comment by matteotenca** [comment]
@pkoutoupis @juanpc2018 

Sorry if I did not posted more details in my first answer. I reproducted the error:

```
shub@gturismo:~/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0$ make
make -C src
make[1]: Entering directory '/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/src'
cc -c json.c -o json.o
cc -c rdsk.c -o rdsk.o
cc -c nvmet.c -o nvmet.o
cc -c sys.c -o sys.o
cc main.c -o rapiddisk json.o nvmet.o rdsk.o sys.o -ljansson
cc -c json.c -DSERVER -o json-server.o
cc -c net.c -o net.o
cc -c sys.c -DSERVER -o sys-server.o
cc daemon.c -o rapiddiskd json-server.o net.o sys-server.o -lpthread -ljansson -lmicrohttpd
Make has completed.
make[1]: Leaving directory '/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/src'
make -C conf
make[1]: Entering directory '/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/conf'
Nothing to do.
make[1]: Leaving directory '/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/conf'
make -C doc
make[1]: Entering directory '/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/doc'
Nothing to do.
make[1]: Leaving directory '/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/doc'
make -C module
make[1]: Entering directory '/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/module'
make -C /lib/modules/5.4.0-91-generic/build M=/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/module
make[2]: Entering directory '/usr/src/linux-headers-5.4.0-91-generic'
make[2]: *** No rule to make target 'Rapidisc/rapiddisk-8.1.0/module'.  Stop.
make[2]: Leaving directory '/usr/src/linux-headers-5.4.0-91-generic'
make[1]: *** [Makefile:37: all] Error 2
make[1]: Leaving directory '/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/module'
make: *** [Makefile:26: module] Error 2
shub@gturismo:~/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0$
```

`make` considers the part of the line after the blank (`Rapidisc/rapiddisk-8.1.0/module`) as a second target to build. I gave a look to the kernel modules build docs, but all the examples I found never used a path with whitespaces after the `M=`. I found out the path after `M=` must be absolute, but nothing more. So I tried to modify the Makefile in such a way that the path was:

1. enclosed in `"` as `M="/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/module"`
2. encloded in `'` as `M='/home/shub/Documents/mine/Linux Rapidisc/rapiddisk-8.1.0/module'`
3. with the blank escaped as `M=/home/shub/Documents/mine/Linux\ Rapidisc/rapiddisk-8.1.0/module`

But none of these worked. Then I found that stackexchange.com answer.

I tried to rename the `Linux Rapidisc` folder to `Linux_Rapidisc` and this solved the problem:

```
shub@gturismo:~/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0$ make
make -C src
make[1]: Entering directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/src'
cc -c json.c -o json.o
cc -c rdsk.c -o rdsk.o
cc -c nvmet.c -o nvmet.o
cc -c sys.c -o sys.o
cc main.c -o rapiddisk json.o nvmet.o rdsk.o sys.o -ljansson
cc -c json.c -DSERVER -o json-server.o
cc -c net.c -o net.o
cc -c sys.c -DSERVER -o sys-server.o
cc daemon.c -o rapiddiskd json-server.o net.o sys-server.o -lpthread -ljansson -lmicrohttpd
Make has completed.
make[1]: Leaving directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/src'
make -C conf
make[1]: Entering directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/conf'
Nothing to do.
make[1]: Leaving directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/conf'
make -C doc
make[1]: Entering directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/doc'
Nothing to do.
make[1]: Leaving directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/doc'
make -C module
make[1]: Entering directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module'
make -C /lib/modules/5.4.0-91-generic/build M=/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module
make[2]: Entering directory '/usr/src/linux-headers-5.4.0-91-generic'
  AR      /home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module/built-in.a
  CC [M]  /home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module/rapiddisk.o
  CC [M]  /home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module/rapiddisk-cache.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC [M]  /home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module/rapiddisk-cache.mod.o
  LD [M]  /home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module/rapiddisk-cache.ko
  CC [M]  /home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module/rapiddisk.mod.o
  LD [M]  /home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module/rapiddisk.ko
make[2]: Leaving directory '/usr/src/linux-headers-5.4.0-91-generic'
make[1]: Leaving directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/module'
make -C test
make[1]: Entering directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/test'
cc rxflush.c -o rxflush
cc rxio.c -o rxio
cc rxioctl.c -o rxioctl
Make has completed.
make[1]: Leaving directory '/home/shub/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0/test'
shub@gturismo:~/Documents/mine/Linux_Rapidisc/rapiddisk-8.1.0$
```

Bye!

**Comment by pkoutoupis** [comment]
Thank you @matteotenca!

@juanpc2018 Are you still having issues building?
