### ISSUE TITLE
Active: failed (Result: exit-code) Kubuntu 21.10

### ISSUE THREAD

**Issue by juanpc2018** [pkoutoupis/rapiddisk#96]
$ systemctl status rapiddiskd.service
× rapiddiskd.service - A rapiddisk network management daemon
     Loaded: loaded (/etc/systemd/system/rapiddiskd.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-05-26 20:21:16 -05; 59s ago
    Process: 151682 ExecStartPre=sh -c lsmod | grep -q rapiddisk || { modprobe rapiddisk ; modprobe rapiddisk-cache ; } (code=exited, status=0/SUCCESS)
    Process: 151685 ExecStart=/sbin/rapiddiskd (code=exited, status=255/EXCEPTION)
        CPU: 18ms

May 26 20:21:16 P-7805u systemd[1]: rapiddiskd.service: Scheduled restart job, restart counter is at 5.
May 26 20:21:16 P-7805u systemd[1]: Stopped A rapiddisk network management daemon.
May 26 20:21:16 P-7805u systemd[1]: rapiddiskd.service: Start request repeated too quickly.
May 26 20:21:16 P-7805u systemd[1]: rapiddiskd.service: Failed with result 'exit-code'.
May 26 20:21:16 P-7805u systemd[1]: Failed to start A rapiddisk network management daemon.

~/Descargas/LinuxRapidisc/rapiddisk-master$ systemctl start rapiddiskd.service
Job for rapiddiskd.service failed because the control process exited with error code.
See "systemctl status rapiddiskd.service" and "journalctl -xeu rapiddiskd.service" for details.

---------
$ journalctl -xeu rapiddiskd.service
░░ 
░░ The unit rapiddiskd.service has entered the 'failed' state with result 'exit-code'.
May 26 20:22:28  systemd[1]: Failed to start A rapiddisk network management daemon.
░░ Subject: A start job for unit rapiddiskd.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit rapiddiskd.service has finished with a failure.
░░ 
░░ The job identifier is 319452 and the job result is failed.
May 26 20:22:29  systemd[1]: rapiddiskd.service: Scheduled restart job, restart counter is at 5.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ Automatic restarting of the unit rapiddiskd.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
May 26 20:22:29  systemd[1]: Stopped A rapiddisk network management daemon.
░░ Subject: A stop job for unit rapiddiskd.service has finished
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A stop job for unit rapiddiskd.service has finished.
░░ 
░░ The job identifier is 319529 and the job result is done.
May 26 20:22:29  systemd[1]: rapiddiskd.service: Start request repeated too quickly.
May 26 20:22:29  systemd[1]: rapiddiskd.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit rapiddiskd.service has entered the 'failed' state with result 'exit-code'.
May 26 20:22:29  systemd[1]: Failed to start A rapiddisk network management daemon.
░░ Subject: A start job for unit rapiddiskd.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit rapiddiskd.service has finished with a failure.
░░ 
░░ The job identifier is 319529 and the job result is failed.

**Comment by pkoutoupis** [comment]
@juanpc2018 Thank you for submitting this. A few questions:
* Can you verify that rapiddisk, rapiddisk-cache and dm-writecache are loaded? If not, can you ensure that they are loaded and restart?
* Is this after a fresh reboot? What happens if you manually start it?

**Comment by juanpc2018** [comment]
Reboot seems to be Like Magic.

-----
$ sudo rapiddisk -h
[sudo] password: 

Please ensure that the RapidDisk module is loaded and retry.

:~$ systemctl status rapiddiskd.service
○ rapiddiskd.service - A rapiddisk network management daemon
     Loaded: loaded (/etc/systemd/system/rapiddiskd.service; disabled; vendor preset: enabled)
     Active: inactive (dead)

:~$ systemctl start rapiddiskd.service

:~$ systemctl status rapiddiskd.service
● rapiddiskd.service - A rapiddisk network management daemon
     Loaded: loaded (/etc/systemd/system/rapiddiskd.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-05-27 11:24:00 -05; 2s ago
    Process: 26682 ExecStartPre=sh -c lsmod | grep -q rapiddisk || { modprobe rapiddisk ; modprobe rapiddisk-cache>
    Process: 26696 ExecStart=/sbin/rapiddiskd (code=exited, status=0/SUCCESS)
   Main PID: 26701 (rapiddiskd)
      Tasks: 3 (limit: 9303)
     Memory: 3.1M
        CPU: 49ms
     CGroup: /system.slice/rapiddiskd.service
             └─26701 /sbin/rapiddiskd

May 27 11:24:00  systemd[1]: Starting A rapiddisk network management daemon...
May 27 11:24:00  rapiddiskd[26701]: rapiddiskd: Daemon started.
May 27 11:24:00  rapiddiskd[26696]: rapiddiskd 8.1.0
May 27 11:24:00  rapiddiskd[26696]: Copyright 2011 - 2022 Petros Koutoupis
May 27 11:24:00  systemd[1]: Started A rapiddisk network management daemon.

:~$ rapiddisk -h

You must be root or contain sudo permissions to initiate this

:~$ sudo rapiddisk -h
rapiddisk 8.1.0
Copyright 2011 - 2022 Petros Koutoupis

rapiddisk is an administration tool to manage RapidDisk RAM disk devices and
        RapidDisk-Cache mappings.

Usage: rapiddisk [ -h | -v ] function [ parameters ]

Description:
        rapiddisk is a RapidDisk module management tool to manage RapidDisk
        RAM disk devices. Dynamically create, remove, resize RAM volumes and if
        desired, map or unmap them as a cache volume to any block device.

Functions:
        -a              Attach RAM disk device (size in MBytes).
        -b              Backend block device absolute path (for cache mapping).
        -c              Input capacity for size or resize of RAM disk device (in MBytes).
        -d              Detach RAM disk device.
        -e              Export a RapidDisk block device as an NVMe Target.
        -f              Erase all data to a specified RapidDisk device (dangerous).
        -H              The host to export / unexport the NVMe Target to / from.
        -h              Display the help menu.
        -i              Define the network interface to enable for NVMe Target exporting.
        -j              Enable JSON formatted output.
        -l              List all attached RAM disk devices.
        -m              Map an RapidDisk device as a caching node to another block device.
        -N              List only enabled NVMe Target ports.
        -n              List RapidDisk enabled NVMe Target exports.
        -P              The port to export / unexport the NVMe Target to / from.
        -p              Define cache policy: write-through, write-around or writeback (dangerous)
                        (default: write-through). Writeback caching is supplied by the dm-writecache
                        kernel module and is not intended for production use as it may result in data
                        loss on hardware/power failure.
        -r              Dynamically grow the size of an existing RapidDisk device.
        -s              Obtain RapidDisk-Cache Mappings statistics.
        -t              Define the NVMe Target port's transfer protocol (i.e. tcp or rdma).
        -u              Unmap a RapidDisk device from another block device.
        -v              Display the utility version string.
        -X              Remove the NVMe Target port (must be unused).
        -x              Unexport a RapidDisk block device from an NVMe Target.

Example Usage:
        rapiddisk -a 64
        rapiddisk -d rd2
        rapiddisk -r rd2 -c 128
        rapiddisk -m rd1 -b /dev/sdb
        rapiddisk -m rd1 -b /dev/sdb -p wt
        rapiddisk -m rd3 -b /dev/mapper/rc-wa_sdb -p wb
        rapiddisk -u rc-wt_sdb
        rapiddisk -f rd2
        rapiddisk -i eth0 -P 1 -t tcp
        rapiddisk -X -P 1
        rapiddisk -e -b rd3 -P 1 -H nqn.host1
        rapiddisk -x -b rd3 -P 1 -H nqn.host1

:~$
