### ISSUE TITLE
Low performance cache Benchmark ?

### ISSUE THREAD

**Issue by juanpc2018** [pkoutoupis/rapiddisk#98]
need to do more tests tomorrow, im half sleep.
but i think i have low perfomance when ramdrive is used as cache.
$ systemctl status rapiddiskd.service
$ systemctl start rapiddiskd.service
$ sudo rapiddisk -a 1000
$ sudo rapiddisk -l
$ sudo rapiddisk -m rd0 -b /dev/sda4
$ sudo rapiddisk -l

to mount was easy in Dolphin,
rapiddisk creates a cloned virtual drive /dev/mapping/rc-wt_sda4
$ lsblk
$ sudo mount /dev/mapper/rc-wt_sda4 ramdisk
or /media/k/ssd same name?

But 
$ genome-disks 
Benchmark Write & Access is very slow.

rapiddisk as Standard RamDrive XFS or Ext4 goes at 11GB/s Read,
5GB/s R&W simultaneously. 5000MB/s

but as cache has super slow Write and Access. 0.11ms - 0.14ms

Maybe is the way i have configured Swap partition? 90% Ram.

----------
Is possible to make cache boot in Grub ?
to make Main drive, similar to intel Optane or Apple FusionDrive ? or Samsung Magician ?

**Comment by pkoutoupis** [comment]
When mapping a RAM drive as a read through cache (or any cache for that matter), it will not be 1:1 to a stand alone RAM drive. The internal caching logic will introduce latencies as tables are looked up for already cached data, etc. The thing to note with your above configuration is that your writes will not see a boost but your reads could potentially see a boost when accessing already cached data.

Also, yes, you can enable the boot/main drive for caching BUT if you do it as a write cache, there is the potential for losing write data and corrupting the root file system. See more here: [https://github.com/pkoutoupis/rapiddisk/tree/master/scripts/rapiddisk-rootdev](https://github.com/pkoutoupis/rapiddisk/tree/master/scripts/rapiddisk-rootdev)
